### PR TITLE
NSG, add local IP into NSG evaluation.

### PR DESCRIPTION
**Pull request by abhijitherekar**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "local-ip",
    "component": "backend",
    "pr-id": "1666",
    "commit-sha": "4d80f6e961756adae12070af4a69b9c99184f768",
    "pipeline": "master"
  },
  {
    "project": "local-ip",
    "component": "gaia",
    "pr-id": "793",
    "commit-sha": "94dc13892b0953c020392bbcd652d2a6cf00b1e1",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "local-ip",
    "component": "gaia",
    "pr-id": "793",
    "commit-sha": "af5c44939fc727baafa1f68d9b78504e9022a2ab",
    "pipeline": "master"
  },
  {
    "project": "local-ip",
    "component": "backend",
    "pr-id": "1666",
    "commit-sha": "4d80f6e961756adae12070af4a69b9c99184f768",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "local-ip",
    "component": "gaia",
    "pr-id": "793",
    "commit-sha": "af5c44939fc727baafa1f68d9b78504e9022a2ab",
    "pipeline": "master"
  },
  {
    "project": "local-ip",
    "component": "backend",
    "pr-id": "1666",
    "commit-sha": "02cf405f0e07c2a4e43b7d175dc47f612435042d",
    "pipeline": "master"
  }
]
```

**Review by rramalinga — APPROVED** [review]

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "local-ip",
    "component": "gaia",
    "pr-id": "793",
    "commit-sha": "af5c44939fc727baafa1f68d9b78504e9022a2ab",
    "pipeline": "master"
  },
  {
    "project": "local-ip",
    "component": "backend",
    "pr-id": "1666",
    "commit-sha": "5424256d013cd9c2dbcb5572a262153142111bc7",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "local-ip",
    "component": "gaia",
    "pr-id": "793",
    "commit-sha": "af5c44939fc727baafa1f68d9b78504e9022a2ab",
    "pipeline": "master"
  },
  {
    "project": "local-ip",
    "component": "backend",
    "pr-id": "1666",
    "commit-sha": "0fc2968eeb71e9306638df2addc15c4a868adc3d",
    "pipeline": "master"
  }
]
```

**Pull request merged**
