### PR TITLE
New: Reputation API for PANDB info retrieval

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
This model is to support the reputation information coming from PANDB on an IP or FQDN (https://redlock.atlassian.net/browse/CNS-3974).

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reputation-api",
    "component": "backend",
    "pr-id": "1724",
    "commit-sha": "76196767d56284928d0ef6beacd7abdb2332dfb0",
    "pipeline": "master"
  },
  {
    "project": "reputation-api",
    "component": "gaia",
    "pr-id": "808",
    "commit-sha": "b0b833f99e14e08e0513f00f454990b5839d188c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reputation-api",
    "component": "backend",
    "pr-id": "1724",
    "commit-sha": "6610b165858a445a5920133410a525d81bcf3083",
    "pipeline": "master"
  },
  {
    "project": "reputation-api",
    "component": "gaia",
    "pr-id": "808",
    "commit-sha": "b0b833f99e14e08e0513f00f454990b5839d188c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reputation-api",
    "component": "backend",
    "pr-id": "1724",
    "commit-sha": "6610b165858a445a5920133410a525d81bcf3083",
    "pipeline": "master"
  },
  {
    "project": "reputation-api",
    "component": "gaia",
    "pr-id": "808",
    "commit-sha": "b0b833f99e14e08e0513f00f454990b5839d188c",
    "pipeline": "master"
  }
]
```

**Review by t00f — DISMISSED** [review]
Looks good to me

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reputation-api",
    "component": "backend",
    "pr-id": "1724",
    "commit-sha": "2a721adbc9121aed3304274ee07b85a286e151c9",
    "pipeline": "master"
  },
  {
    "project": "reputation-api",
    "component": "gaia",
    "pr-id": "808",
    "commit-sha": "7be4f5e0d4f4f7b75c40fcbc69770898db8e51f8",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reputation-api",
    "component": "backend",
    "pr-id": "1724",
    "commit-sha": "c97853baf39b4c8a4ae5658f9f4c5cc054c3af7c",
    "pipeline": "master"
  },
  {
    "project": "reputation-api",
    "component": "gaia",
    "pr-id": "808",
    "commit-sha": "caef076b56b76312dc22cc7619a15f61e96bf081",
    "pipeline": "master"
  }
]
```

**Pull request merged**
