### PR TITLE
Alert Integration Phase 2

### PR DESCRIPTION
**Pull request by rramalinga**
## Description

These gaia changes includes objects which are required to resolve alerts with PC. The cloudalertrecord is created for every alert that is raised with PC. The record contains information to detect how recent the alert is which helps in resolving the alert when the alert is not raise anymore. It also has information on if the alert is published with PC.

### CODE REVIEW

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "b342430d19c2fcc5959fda67bf919f9225d13500",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "24c64158cd8e6f5e5130110264ef0a2d5b34379e",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "b342430d19c2fcc5959fda67bf919f9225d13500",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "24c64158cd8e6f5e5130110264ef0a2d5b34379e",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "1261e3407cbf0077ea1e9841446d3f1660154259",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "24c64158cd8e6f5e5130110264ef0a2d5b34379e",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "24c64158cd8e6f5e5130110264ef0a2d5b34379e",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "9b248519a30908467c3c7e6bd1ed4d27e0628d93",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "477ec4d2ed456a0b11855bdc72bba1e0cecd289b",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "24c64158cd8e6f5e5130110264ef0a2d5b34379e",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "24c64158cd8e6f5e5130110264ef0a2d5b34379e",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "b86c40cff37e09badd22cb46a66a0f8ee3438b07",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "086429afade494902f7843d16ba6060846d65dcd",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "ed80ba8ea46d6721fed0a1bae2c2c1baab18d801",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "ed80ba8ea46d6721fed0a1bae2c2c1baab18d801",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "086429afade494902f7843d16ba6060846d65dcd",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "79bd3a978f15760d19ac74d88d001ef8498d25fb",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "ed80ba8ea46d6721fed0a1bae2c2c1baab18d801",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-2",
    "component": "gaia",
    "pr-id": "712",
    "commit-sha": "ed80ba8ea46d6721fed0a1bae2c2c1baab18d801",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "prismacloud",
    "pr-id": "58",
    "commit-sha": "bf679cc6b0ff7dd6b67ae0ecb8433166081a7ad1",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-2",
    "component": "backend",
    "pr-id": "1365",
    "commit-sha": "97fe65fa06ceabe47d09e5b4ee3f7a3e9db7ffa2",
    "pipeline": "master"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
