### PR TITLE
windows-service-type

### PR DESCRIPTION
**Pull request by Rohit4793**
## Description

> Fixes #.
https://redlock.atlassian.net/browse/CNS-139

### CODE REVIEW

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "e3c0338bca54b0a7a72ad15cfcd8506f47e5b6ed",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "fcc18dcfe0d32b0f3757cf91d091ba336aad60f8",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "e9cf061d8ce06673108623359164bb442879dd55",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "29ef8cc3ef0ac85ab4402eec1d107fce37f0c673",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "4d33682211f59c9582f5027ca61a4ab6a2f7374f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "3dc05975e06c753d03a4641d24e4d48ef8e6eee6",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "44a2d7a4d2b0d365e600f87c090df74a95ef92b7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "4d33682211f59c9582f5027ca61a4ab6a2f7374f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "3dc05975e06c753d03a4641d24e4d48ef8e6eee6",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "4d33682211f59c9582f5027ca61a4ab6a2f7374f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "3dc05975e06c753d03a4641d24e4d48ef8e6eee6",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "064815d148407bde4a4149530fad718c8f3271ab",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "ca818b71db962e7c8526add497c41f475bdcaff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "ffee3c86b19f531364db172b110532ddc4a7a38a",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "064815d148407bde4a4149530fad718c8f3271ab",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "be89acff98d1bdd63f658cfea7cc5ed1f753e1f4",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "ca818b71db962e7c8526add497c41f475bdcaff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "facc249d369a8742d60ea105e45dca26c63962a2",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "ca818b71db962e7c8526add497c41f475bdcaff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "facc249d369a8742d60ea105e45dca26c63962a2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "ef0fc9c8c72cbef3437a3634575a09befc2bfe31",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "7088af603450a3f898ee6b46ef4eef327e57bf8f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "b47ba10bedca009cb2db39d0cc4b6e8aec5513df",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "ca818b71db962e7c8526add497c41f475bdcaff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "facc249d369a8742d60ea105e45dca26c63962a2",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "ca818b71db962e7c8526add497c41f475bdcaff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "facc249d369a8742d60ea105e45dca26c63962a2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "b47ba10bedca009cb2db39d0cc4b6e8aec5513df",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests-lib",
    "pr-id": "402",
    "commit-sha": "ca818b71db962e7c8526add497c41f475bdcaff7",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2879",
    "commit-sha": "facc249d369a8742d60ea105e45dca26c63962a2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "b47ba10bedca009cb2db39d0cc4b6e8aec5513df",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "b635ef828520b6a0f7cef78fa0f375280004c255",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "b1392d610d32877214304ff586f1356824cb6286",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3016",
    "commit-sha": "ed56d4a45f62036010865fcd2b74098675a3f7ca",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "d2781b6c7ffa132e88f7ef9166258c60d531fa27",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3016",
    "commit-sha": "ed56d4a45f62036010865fcd2b74098675a3f7ca",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "1865f4324bc88b8e2596116eddefff34469af79e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3016",
    "commit-sha": "ed56d4a45f62036010865fcd2b74098675a3f7ca",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "c7542190da4ac65c89039a005612b30d2fedc982",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3016",
    "commit-sha": "ed56d4a45f62036010865fcd2b74098675a3f7ca",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "17490110fae6e6bd2cbd04f22fea5c404a9644ae",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3016",
    "commit-sha": "8353f17ebfc3d0ce595a48b72b661fe3fca8df71",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "945",
    "commit-sha": "f74b621a860306c7c16a6650ec5babe96fc38448",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "b06b184680199a7e4dcfcbede6b10631619bafb2",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3016",
    "commit-sha": "8353f17ebfc3d0ce595a48b72b661fe3fca8df71",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "952",
    "commit-sha": "0fae79638e7a1349747d985b901a6e119b99636c",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "579",
    "commit-sha": "cf9579f97952e9a6fe0e2e2a021b15caa66dd510",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2134",
    "commit-sha": "17490110fae6e6bd2cbd04f22fea5c404a9644ae",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
