### PR TITLE
Fix port validation in all places

### PR DESCRIPTION
**Pull request by dstiliadis**
This fixes the port validation to allow TCP ports of 0 in all validation checks (portutils used by services and NEP)

### CODE REVIEW

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "e38bba7c7540adef6b220a51efd262a689220611",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "b099ff5db18a9b5722025bd5d44b80f23a81e086",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "b099ff5db18a9b5722025bd5d44b80f23a81e086",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "b099ff5db18a9b5722025bd5d44b80f23a81e086",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "53b1fde6fa056c2e35ff81b949698077720418d2",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "4dd2ec7bfab8a047dc06bd2deca308aec6356865",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "9efd50f6fa4a3f3088b2cd1d09859eb75bf2b30e",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "4dd2ec7bfab8a047dc06bd2deca308aec6356865",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "311a3f9b933793867438b8a181cdaa0a63b73aec",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "febcd5529227d24b991234df64611cc3d32d4d81",
    "pipeline": "master"
  }
]
```

**Review by ericrpowers — APPROVED** [review]

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "tgw",
    "component": "backend",
    "pr-id": "1254",
    "commit-sha": "e58b9d7fcd2f6bc459fb2c90d98f105e311e5620",
    "pipeline": "master"
  },
  {
    "project": "tgw",
    "component": "gaia",
    "pr-id": "675",
    "commit-sha": "311a3f9b933793867438b8a181cdaa0a63b73aec",
    "pipeline": "master"
  }
]
```

**Pull request merged**
