### PR TITLE
Update: Add results to metricsquery and metricsqueryrange

### PR DESCRIPTION
**Pull request by ericrpowers**

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "19fe2a36f44f7b2418cc770b8421cda7bf2d4e2a",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "727aa199d6e3435e198f989693adde7f5a6e672f",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "f38e396fe480d50a46557c2f20ebba1d8a044117",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "0f3ffe17d11da0bb36752712e479f6348d1982ca",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "715a56ab1237d28e5d61592bdb6c673171772d18",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "91afbd4792b92246ec4395c15993627f56e70e56",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "2ebc4adde25bd67ac33015b6e9a5ae89622c2ef0",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "43d49c9fa889e73786e50defc4edec4778d5c195",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "deac64e2ba839e6f5e48f93b7c2ea2aae0aa76be",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "b66fb8ea3742fc041ae7d2148862916b4d3502fe",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "c25230f04d9cc2968bedc50bb695ced52a18942c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "vm-metrics-accessibility",
    "component": "backend",
    "pr-id": "1676",
    "commit-sha": "aa3a842233d29d9636dce947e8cae40632716687",
    "pipeline": "master"
  },
  {
    "project": "vm-metrics-accessibility",
    "component": "gaia",
    "pr-id": "798",
    "commit-sha": "b58f026ee58e610719537b0dffa12a38ff95da0b",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
