### PR TITLE
[aws/gcp/azure] Store PrismaAPIID

### PR DESCRIPTION
**Pull request by malkhamis-panw**
Commits are independent

### CODE REVIEW

**Review by sawyerawesome — APPROVED** [review]
lgtm

**Review by kcarrasco-panw — APPROVED** [review]

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "700",
    "commit-sha": "18bcfb0b",
    "commit-full-sha": "18bcfb0bd37a7145ee8f72ca613ae75fb5717ac1",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "358dc61b",
    "commit-full-sha": "358dc61b8f609f87d16172dee4f23e8e4b75ec3f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "358dc61b",
    "commit-full-sha": "358dc61b8f609f87d16172dee4f23e8e4b75ec3f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "358dc61b",
    "commit-full-sha": "358dc61b8f609f87d16172dee4f23e8e4b75ec3f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "358dc61b",
    "commit-full-sha": "358dc61b8f609f87d16172dee4f23e8e4b75ec3f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "bc59cc67",
    "commit-full-sha": "bc59cc67c588f8727cf3d53cf70daa1fa61afad7",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "bc59cc67",
    "commit-full-sha": "bc59cc67c588f8727cf3d53cf70daa1fa61afad7",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "ced8b0f2",
    "commit-full-sha": "ced8b0f2569a90088caf0609424329832e6dc899",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "958",
    "commit-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "commit-full-sha": "ddd42e8a07962a299e1dff2f697770d796aead7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "799",
    "commit-sha": "ced8b0f2",
    "commit-full-sha": "ced8b0f2569a90088caf0609424329832e6dc899",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by malkhamis-panw** [comment]
Merging this will break pccnabackend master.... but Gitlab is degraded and gogo won't capture this MR for some reason!!

**Pull request merged**
