### PR TITLE
Add more validations to network rule sets

### PR DESCRIPTION
**Pull request by malkhamis-panw**
Reference JIRA tickets:
- https://redlock.atlassian.net/browse/CNS-2134
- https://redlock.atlassian.net/browse/CNS-1171

### CODE REVIEW

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "61893b148c731b7c829566c2588d41346b7cc3a5",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "eddd3dda15be918b35d53606f5aba247a42d2c3e",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "eddd3dda15be918b35d53606f5aba247a42d2c3e",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "61893b148c731b7c829566c2588d41346b7cc3a5",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "61893b148c731b7c829566c2588d41346b7cc3a5",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "eddd3dda15be918b35d53606f5aba247a42d2c3e",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "b85ae7837d5ed307fca2ab9f4c7fec446077a39b",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "eddd3dda15be918b35d53606f5aba247a42d2c3e",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "b85ae7837d5ed307fca2ab9f4c7fec446077a39b",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "78a868d2e9a10b0b9b266e215bfc18abb476b9df",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "6766e7fca6286d05f725aec0ae78b27cb85c214e",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]
I'm not sure about the relevance of having all these validation functions separated in the long run. These makes the system more flexible for sure, but also these rules are good and should apply to every tag expression under the sun. People will probably always forget to add those in addition to $tagExpression

We may need to move the to $tagexpression later

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "6a27c3dfd744ac2d7677d9bf761c8d4ae8a602d4",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "apotests",
    "pr-id": "3412",
    "commit-sha": "1c245b439d55cc52a61eda241944d2db6ca3be8f",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "6a27c3dfd744ac2d7677d9bf761c8d4ae8a602d4",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "network-rule-validation",
    "component": "backend",
    "pr-id": "1204",
    "commit-sha": "6a27c3dfd744ac2d7677d9bf761c8d4ae8a602d4",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "gaia",
    "pr-id": "661",
    "commit-sha": "4639ce67e4f258659aae610271712bdff76c5ce3",
    "pipeline": "master"
  },
  {
    "project": "network-rule-validation",
    "component": "apotests",
    "pr-id": "3412",
    "commit-sha": "1e77770092d609ae0dab1b9385b74d5f7adf8d84",
    "pipeline": "master"
  }
]
```

**Pull request merged**
