### PR TITLE
[CNS-8189] neocna/aws: support lambda function, rds db instance and redshift cluster resources

### PR DESCRIPTION
**Pull request by kcarrasco-panw**
Part of CNS-8189

### CODE REVIEW

**Comment by kcarrasco-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "800",
    "commit-sha": "0f3aac9c",
    "commit-full-sha": "0f3aac9c7795364ada29e7ad9c339f82713fb5cf",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "959",
    "commit-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "commit-full-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by kcarrasco-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "800",
    "commit-sha": "0de74505",
    "commit-full-sha": "0de74505362d62d9f8c20851f9e58a5c4fa61e3e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "959",
    "commit-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "commit-full-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by kcarrasco-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "959",
    "commit-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "commit-full-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "800",
    "commit-sha": "0de74505",
    "commit-full-sha": "0de74505362d62d9f8c20851f9e58a5c4fa61e3e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by kcarrasco-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "800",
    "commit-sha": "0de74505",
    "commit-full-sha": "0de74505362d62d9f8c20851f9e58a5c4fa61e3e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "959",
    "commit-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "commit-full-sha": "c0dcb156fd897a0df9e618d9bcd0c6632269b1a2",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Review by malkhamis-panw — APPROVED** [review]

**Pull request merged**
