### PR TITLE
Update: Remove v1 external network support

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
It is about time to remove v1 external network support and enforce v2 syntax `servicePorts`.

### CODE REVIEW

**Review by t00f — APPROVED** [review]

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "remove-external-network-v1",
    "component": "aporeliable",
    "pr-id": "95",
    "commit-sha": "0a48ea243a51808e8aa0ae05c69287a512916350",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "2962582d8fda263c196dfbe4450066328d637f74",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "cookbook",
    "pr-id": "25",
    "commit-sha": "4b4628d4ef58431dafdd203b4b5522c1afff120d",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "apotests",
    "pr-id": "2854",
    "commit-sha": "699f3c4a219389f6d3eb9756844b22069b17413e",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "benchmark-suite",
    "pr-id": "562",
    "commit-sha": "f5dd9f41a225f2fb2a5588fa1515654148880f48",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "reliability-apps",
    "pr-id": "11",
    "commit-sha": "ed6c8862c497be0db6b1895f21afa030caead739",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "apoctl",
    "pr-id": "272",
    "commit-sha": "9e18f94a3c2d768df3b50badc11862a24bac934f",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "junon",
    "pr-id": "602",
    "commit-sha": "f20c18d1285ade52825477c5128a317c09326a49",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "aporeto-operator",
    "pr-id": "140",
    "commit-sha": "a7256418d30702c3c3dc48b132e538843f8e91d2",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "remove-external-network-v1",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "cookbook",
    "pr-id": "25",
    "commit-sha": "4b4628d4ef58431dafdd203b4b5522c1afff120d",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "benchmark-suite",
    "pr-id": "562",
    "commit-sha": "f5dd9f41a225f2fb2a5588fa1515654148880f48",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "apotests",
    "pr-id": "2854",
    "commit-sha": "699f3c4a219389f6d3eb9756844b22069b17413e",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "reliability-apps",
    "pr-id": "11",
    "commit-sha": "ed6c8862c497be0db6b1895f21afa030caead739",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "2962582d8fda263c196dfbe4450066328d637f74",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "aporeto-operator",
    "pr-id": "140",
    "commit-sha": "a7256418d30702c3c3dc48b132e538843f8e91d2",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "aporeliable",
    "pr-id": "95",
    "commit-sha": "0a48ea243a51808e8aa0ae05c69287a512916350",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  },
  {
    "project": "remove-external-network-v1",
    "component": "apoctl",
    "pr-id": "272",
    "commit-sha": "9e18f94a3c2d768df3b50badc11862a24bac934f",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2854",
    "commit-sha": "699f3c4a219389f6d3eb9756844b22069b17413e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apoctl",
    "pr-id": "272",
    "commit-sha": "9e18f94a3c2d768df3b50badc11862a24bac934f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "2962582d8fda263c196dfbe4450066328d637f74",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "aporeto-operator",
    "pr-id": "140",
    "commit-sha": "a7256418d30702c3c3dc48b132e538843f8e91d2",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "benchmark-suite",
    "pr-id": "562",
    "commit-sha": "f5dd9f41a225f2fb2a5588fa1515654148880f48",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "f60c9ec3804655de998b474a179c90caaea8d778",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "f60c9ec3804655de998b474a179c90caaea8d778",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "apotests",
    "pr-id": "2854",
    "commit-sha": "36775254faaa3f07cc8dd6adf0643c3259311a5c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "c709956b8c7fe26d098a86ce3ac4757f0b275902",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "c709956b8c7fe26d098a86ce3ac4757f0b275902",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "201c1788946de31b897648666d34903aefdf368f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "850",
    "commit-sha": "201c1788946de31b897648666d34903aefdf368f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "545",
    "commit-sha": "154b8fafc7c98056b82e082f9677f25366c074e5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "underwater",
    "pr-id": "119",
    "commit-sha": "ecdf70c9162d48a5ab73d37b10d19d2950bd6261",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
