### PR TITLE
bugfix/caitsith: remove unnecessary custom validation

### PR DESCRIPTION
**Pull request by malkhamis-panw**
It turns out that we can store api authz policies with empty AuthorizedNamespaces.. After all, we should assume the `req.Namespace` if no AuthorizaedNamepaces were given at all..

### CODE REVIEW

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-apiauthzpol-migration-race",
    "component": "gaia",
    "pr-id": "752",
    "commit-sha": "a4097046f226113ebcf622bb6f0617b66eb58c03",
    "pipeline": "master"
  },
  {
    "project": "bugfix-apiauthzpol-migration-race",
    "component": "backend",
    "pr-id": "1506",
    "commit-sha": "3308829d4898eb194051d8b258afd1b3b8666b95",
    "pipeline": "master"
  }
]
```

**Review by ericrpowers — COMMENTED** [review]
I think this is missing removing the mapping in `_validation.mapping`. LGTM otherwise.

**Comment by primalmotion** [comment]
Just to make sure: you cannot store them empty in the DB. They must be filled at create/update time and stored.

**Comment by malkhamis-panw** [comment]
@primalmotion there will be a check in the processor and if it is empty, it will stick `req.Namespace` as suggested earlier in Slack conv.

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-apiauthzpol-migration-race",
    "component": "gaia",
    "pr-id": "752",
    "commit-sha": "498c9e2da093ec2d5ce759878d36a53cbc17f853",
    "pipeline": "master"
  },
  {
    "project": "bugfix-apiauthzpol-migration-race",
    "component": "backend",
    "pr-id": "1506",
    "commit-sha": "3308829d4898eb194051d8b258afd1b3b8666b95",
    "pipeline": "master"
  }
]
```

**Review by ericrpowers — APPROVED** [review]

**Review by t00f — APPROVED** [review]

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-apiauthzpol-migration-race",
    "component": "gaia",
    "pr-id": "752",
    "commit-sha": "498c9e2da093ec2d5ce759878d36a53cbc17f853",
    "pipeline": "master"
  },
  {
    "project": "bugfix-apiauthzpol-migration-race",
    "component": "backend",
    "pr-id": "1506",
    "commit-sha": "1fa437342a5aa267656e727e036992a00c2b225d",
    "pipeline": "master"
  }
]
```

**Pull request merged**
