### PR TITLE
add AutomationAction as data type to uiparameter

### PR DESCRIPTION
**Pull request by vjuux**

### CODE REVIEW

**Comment by ericrpowers** [comment]
I don't know why this PR has so many extra changes outside yours, but let's separate them to make it clean.

**Comment by vjuux** [comment]
@ericrpowers All this extra stuff is coming from master? This is `codegen` against `uiparameter.spec` change 🤷

**Review by primalmotion — CHANGES_REQUESTED** [review]
There are way too many changes for something seemingly that simple

**Comment by vjuux** [comment]
> There are way too many changes for something seemingly that simple

All this extra stuff seems to be debt from folks not running codegen, shall I just ignore all these changes and commit just `uiparameter.spec` that is required by my change?

**Comment by ericrpowers** [comment]
We need to merge https://github.com/PaloAltoNetworks/gaia/pull/755 first, merge master, then this PR will clean up.

**Comment by vjuux** [comment]
looks much cleaner 😛

**Review by ericrpowers — APPROVED** [review]

**Review by primalmotion — APPROVED** [review]

**Comment by primalmotion** [comment]
@vjuux definitely :)

**Pull request merged**
