### PR TITLE
Update: Add onlyPolicyTags filter on Tag retrievemany

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
We do not want to always enforce tag prefixes when doing a retrievemany on Tags, so we are introducing `onlyPolicyTags` filter to allow enforcing the restriction per demand.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-tags",
    "component": "gaia",
    "pr-id": "596",
    "commit-sha": "c180b440b1f5cff3fccdc3adc9da4fa3e4876630",
    "pipeline": "master"
  },
  {
    "project": "reduce-tags",
    "component": "backend",
    "pr-id": "960",
    "commit-sha": "2a3c05771ba5672db650d2b665850c84b481bfd9",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-tags",
    "component": "backend",
    "pr-id": "960",
    "commit-sha": "8a7762ee646940c939f179a8ec81d4d35b543591",
    "pipeline": "master"
  },
  {
    "project": "reduce-tags",
    "component": "gaia",
    "pr-id": "596",
    "commit-sha": "c180b440b1f5cff3fccdc3adc9da4fa3e4876630",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-tags",
    "component": "backend",
    "pr-id": "960",
    "commit-sha": "1ee8919756ad1bcfc4f12a0924f50fb2f536d172",
    "pipeline": "master"
  },
  {
    "project": "reduce-tags",
    "component": "gaia",
    "pr-id": "596",
    "commit-sha": "c180b440b1f5cff3fccdc3adc9da4fa3e4876630",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-tags",
    "component": "backend",
    "pr-id": "960",
    "commit-sha": "6649b35f2dd2caaa75f48a5b440480fcd8906c2e",
    "pipeline": "master"
  },
  {
    "project": "reduce-tags",
    "component": "gaia",
    "pr-id": "596",
    "commit-sha": "c180b440b1f5cff3fccdc3adc9da4fa3e4876630",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "reduce-tags",
    "component": "backend",
    "pr-id": "960",
    "commit-sha": "6649b35f2dd2caaa75f48a5b440480fcd8906c2e",
    "pipeline": "master"
  },
  {
    "project": "reduce-tags",
    "component": "gaia",
    "pr-id": "596",
    "commit-sha": "c180b440b1f5cff3fccdc3adc9da4fa3e4876630",
    "pipeline": "master"
  }
]
```

**Pull request merged**
