### PR TITLE
Added new flags to cnsconfig for findings integrations

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "385cbf6c93516be1f9ce7e3e78c5387acab390d9",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "50774f17a3c684cfd9cf0758f4131a26c37790aa",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "385cbf6c93516be1f9ce7e3e78c5387acab390d9",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "695a671ba6c78dc60b9c5085db8cd260eda447c4",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "69173de558d26799cc126f651f044886fe7df032",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "0280c92f73c861b6f70b8666f9913973a71fa7f3",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "9ddb14149eaccde89dc84b52f849f50caec98716",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "0280c92f73c861b6f70b8666f9913973a71fa7f3",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "5398ef711fca3289242eb8c00e483fc750d89775",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "0280c92f73c861b6f70b8666f9913973a71fa7f3",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "8c17b7b6fdcf54992e4af1fde4a421a27123158b",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "0280c92f73c861b6f70b8666f9913973a71fa7f3",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "8c17b7b6fdcf54992e4af1fde4a421a27123158b",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "0280c92f73c861b6f70b8666f9913973a71fa7f3",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "0280c92f73c861b6f70b8666f9913973a71fa7f3",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "1d9a1aae929e364ea003cd395dce1e38ebc5304e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "1d9a1aae929e364ea003cd395dce1e38ebc5304e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "8e869b3d2fb48b0a6dbdf865ebaf197c39374f7d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "8e12ed10da6a0411f35fcfdb41ce03b966cb899e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "ea9c25c67d445498f8ca65d3688b55f92ba00a14",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "f302f4e1ca068340e85e0fc6c824fc7a42a7f004",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "baa166d114fac81e3935226fcb5b63270f2248ab",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "8a33ea082ee61058982c7312453544b0ddd8a720",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "baa166d114fac81e3935226fcb5b63270f2248ab",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "8a33ea082ee61058982c7312453544b0ddd8a720",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "8c8febacac387ba106c4abbcc5e3abfda42a4d31",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "a8b98710140ec43ab6b8ab42b0d992696debf632",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "f8ff5d0240f0a7ab09f7ee4ce0d7760309f5440a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "d22b7d5d538ba24ce2e705d891a9af5c9157bb53",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "f8ff5d0240f0a7ab09f7ee4ce0d7760309f5440a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "f8ff5d0240f0a7ab09f7ee4ce0d7760309f5440a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "0635c65193ba5e8bca353eca2a5f2737e380dbd6",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "4232b77a35b60012a332cef5dd735d79074005cc",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "f8ff5d0240f0a7ab09f7ee4ce0d7760309f5440a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "f4f016640ab38b0176cb973e76c069046e2098f2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "9ba9f29e1ceacc0e3a3458dd6c27bb5b4551721c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "803baad209923c515e3bb8f81c2a3d05ce9f7e80",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "28e2e72bad095e7e3469c21031dcff09db49b12a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "03312b5ca5efef0d541a8a744cf18b858ffc6206",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "803baad209923c515e3bb8f81c2a3d05ce9f7e80",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "28e2e72bad095e7e3469c21031dcff09db49b12a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "5c81c2f7037114955bc0857fe97971a7eae29640",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "a5e575d224246de629b00b28d7d425b0eddc9469",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "28e2e72bad095e7e3469c21031dcff09db49b12a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1956",
    "commit-sha": "06b5119879ac3e21c3ee610379b61e96c88fce08",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "857",
    "commit-sha": "d08642f4eff93ecbb49dab25457165ccbbfd4bf1",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "99",
    "commit-sha": "28e2e72bad095e7e3469c21031dcff09db49b12a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
