### PR TITLE
add proxy protocol preserve header (#826)

### PR DESCRIPTION
**Pull request by philipatl**
## Description

backport the "preserve proxy header" option on Services to 5.3

## Types of changes

- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2861",
    "commit-sha": "c8dab1c7aaa054762cb16c590ba6e6e92b46cff3",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "831",
    "commit-sha": "f2b8d3a5bbc97519e0621f4f8f77a1c0934156c7",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "831",
    "commit-sha": "f2b8d3a5bbc97519e0621f4f8f77a1c0934156c7",
    "pipeline": "release-5.3.0"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2861",
    "commit-sha": "c8dab1c7aaa054762cb16c590ba6e6e92b46cff3",
    "pipeline": "release-5.3.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2861",
    "commit-sha": "c8dab1c7aaa054762cb16c590ba6e6e92b46cff3",
    "pipeline": "release-5.3.0"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "831",
    "commit-sha": "f2b8d3a5bbc97519e0621f4f8f77a1c0934156c7",
    "pipeline": "release-5.3.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2861",
    "commit-sha": "c8dab1c7aaa054762cb16c590ba6e6e92b46cff3",
    "pipeline": "release-5.3.0"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "831",
    "commit-sha": "f2b8d3a5bbc97519e0621f4f8f77a1c0934156c7",
    "pipeline": "release-5.3.0"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1856",
    "commit-sha": "e527d6b3a53c7a8d2582cfd01c37563f52bdbe2e",
    "pipeline": "release-5.3.0"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "831",
    "commit-sha": "f2b8d3a5bbc97519e0621f4f8f77a1c0934156c7",
    "pipeline": "release-5.3.0"
  }
]
```

**Review by malkhamis-panw — APPROVED** [review]

**Review by t00f — APPROVED** [review]

**Pull request merged**
