### PR TITLE
added EffectiveSecurityGroup type

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "f79f49e91775bf3608309cc86d6b08834242c53e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "f79f49e91775bf3608309cc86d6b08834242c53e",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "f79f49e91775bf3608309cc86d6b08834242c53e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "50a0e048b3fb77208f5b9042774235c159e121cc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "154ccd446c442704eedbbb6ff38cb06069c6f408",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "0b3c0b636db4e0eefabdd3cca5da139391060ebb",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "bf3e46720c786bee26d7cd48b09f024bb27d27bd",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "6f81fc622298a5ae3eff8a92f9370ece1dc89f98",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "55e17f557c93025e5ec9a69a105f1deb63fdc6b5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "99b44457439700b028d56b70ad2c92b8ddc9b8c5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1723",
    "commit-sha": "34a5b837c8a283c02bffd7833fea4ef68fcb043a",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "809",
    "commit-sha": "a3179f825c099d64de950e167ea6efbd2858fb20",
    "pipeline": "master"
  }
]
```

**Review by ayliao — APPROVED** [review]

**Pull request merged**
