### PR TITLE
new: detected host mode container property on enforcer (#623)

### PR DESCRIPTION
**Pull request by Rohit4793**
>Fixes
https://redlock.atlassian.net/browse/CNS-1502

### CODE REVIEW

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3256",
    "commit-sha": "1727f4b845a85824e64af031bd75aa147fc0639a",
    "pipeline": "release-5.0.0"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2334",
    "commit-sha": "57d22f0a8ff2ce52e58c6add457c646873f977fe",
    "pipeline": "release-5.0.0"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "629",
    "commit-sha": "94f7aa13b9b99b132c087e9e5de1ec6df46c8c6d",
    "pipeline": "release-5.0.0"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3256",
    "commit-sha": "6bcb0cbde30e93c70572d36d8c79755503b92476",
    "pipeline": "release-5.0.0"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2334",
    "commit-sha": "57d22f0a8ff2ce52e58c6add457c646873f977fe",
    "pipeline": "release-5.0.0"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "629",
    "commit-sha": "94f7aa13b9b99b132c087e9e5de1ec6df46c8c6d",
    "pipeline": "release-5.0.0"
  }
]
```

**Comment by Rohit4793** [comment]
This is just a cherry-picked from master PR

**Comment by amitlimaye** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "629",
    "commit-sha": "94f7aa13b9b99b132c087e9e5de1ec6df46c8c6d",
    "pipeline": "release-5.0.0"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2334",
    "commit-sha": "57d22f0a8ff2ce52e58c6add457c646873f977fe",
    "pipeline": "release-5.0.0"
  }
]
```

**Pull request merged**
