### PR TITLE
New: PC token verifier

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
The initial form of the PC token verifier did not allow it to be cleanly registered with the gateway. This will achieve the same behavior while also being cleaner with its integration.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1978",
    "commit-sha": "d95d6acfa7618b1be00370a1e109bac06a827a72",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "869",
    "commit-sha": "9f16ff2daed11ec1f357b4ca4fa09fd302838cf6",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1978",
    "commit-sha": "0d6d413ce759eb1733c8b5ce010ab3e2181c7709",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "869",
    "commit-sha": "9f16ff2daed11ec1f357b4ca4fa09fd302838cf6",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1978",
    "commit-sha": "b897cefe8a3247f83313193a37786c675d611eae",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "869",
    "commit-sha": "9f16ff2daed11ec1f357b4ca4fa09fd302838cf6",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "bahamut",
    "pr-id": "164",
    "commit-sha": "173fc47672a40213b48fb6712e71ae9754330449",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1978",
    "commit-sha": "817fb2cf4aadbe34928e249325d93f7ab9e18942",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "869",
    "commit-sha": "9f16ff2daed11ec1f357b4ca4fa09fd302838cf6",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1978",
    "commit-sha": "99794424d88c896286afb5174453e5527af741db",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "869",
    "commit-sha": "9f16ff2daed11ec1f357b4ca4fa09fd302838cf6",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1978",
    "commit-sha": "9ee77ca809ea0f3ac64973b4489f64f34d91cb3f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "869",
    "commit-sha": "9f16ff2daed11ec1f357b4ca4fa09fd302838cf6",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
