### PR TITLE
Update: Revised namespace types

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
Namespace types have been revised to the following:
- Tenant
- CloudAccount
- HostGroup
- KubernetesClusterGroup
- Kubernetes

The bottom three are new and `Group` is removed.

> Fixes: https://redlock.atlassian.net/browse/CNS-454

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "update-namespace-types",
    "component": "apotests",
    "pr-id": "2953",
    "commit-sha": "61aa64e5c367ca78ee26ebe337ed7ae7227d3310",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "be869ba5063bea302f4702386287fbfa537007a0",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "c628078b5293228fa5ed1da59578ea97b94165c9",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "update-namespace-types",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "35511e7c38eafac5266184f127ce157557f67c91",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "apotests",
    "pr-id": "2953",
    "commit-sha": "61aa64e5c367ca78ee26ebe337ed7ae7227d3310",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "be869ba5063bea302f4702386287fbfa537007a0",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "update-namespace-types",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "be869ba5063bea302f4702386287fbfa537007a0",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "35511e7c38eafac5266184f127ce157557f67c91",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "apotests",
    "pr-id": "2953",
    "commit-sha": "61aa64e5c367ca78ee26ebe337ed7ae7227d3310",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "update-namespace-types",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "be869ba5063bea302f4702386287fbfa537007a0",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "35511e7c38eafac5266184f127ce157557f67c91",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "apotests",
    "pr-id": "2953",
    "commit-sha": "61aa64e5c367ca78ee26ebe337ed7ae7227d3310",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "be869ba5063bea302f4702386287fbfa537007a0",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "965c40344873bbbc33636aab63b4df3a93585391",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "be869ba5063bea302f4702386287fbfa537007a0",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "965c40344873bbbc33636aab63b4df3a93585391",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — DISMISSED** [review]

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "update-namespace-types",
    "component": "gaia",
    "pr-id": "563",
    "commit-sha": "259f702024b7bb1b0b08a8b71dd0d8531de33846",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "backend",
    "pr-id": "899",
    "commit-sha": "366d8ed140a560203076a1d67b20221c0790651c",
    "pipeline": "master"
  },
  {
    "project": "update-namespace-types",
    "component": "apotests",
    "pr-id": "2953",
    "commit-sha": "211dc5a39394e959c0e17d72088fff077ff7d2fb",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
