### PR TITLE
Removes purefresh (not a word)

### PR DESCRIPTION
**Pull request by emanic**
## Description

@CyrilPeponnet : removing `purefresh` 

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by primalmotion — CHANGES_REQUESTED** [review]
PURefresh is the resource name. Should be capitalized

**Comment by emanic** [comment]
Really? I see `ProcessingUnitRefresh` I see `Processing Unit Refresh`. Looking for `PURRefresh` I do not find anything in the entire API document. Meanwhile, I see just `refresh` everywhere else here in this `ProcessingUnitRefresh` section @primalmotion

**Comment by primalmotion** [comment]
Actually, you're right, it is Processing Unit Refresh. It should be called like that, not just refresh, which can be confused with enforcer refresh.

**Comment by emanic** [comment]
Ah OK, makes more sense 👍  OK check it now @primalmotion

**Review by primalmotion — APPROVED** [review]

**Comment by primalmotion** [comment]
Approved. Please next time ask for a review with the button. I basically only look at PRs where I'm explicitly asked for a review :)

**Comment by emanic** [comment]
OK didn't see that button, will use it next time. 👍

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
