### PR TITLE
added port util func for checking contains

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "cba424739da0bc8fa27f80a67b58f154b2771f9e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "148b68de534a0ea513e3c3a8a5f0327dc21a4526",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "e2a737709a84b125a70b81fb2ca534084071308f",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "148b68de534a0ea513e3c3a8a5f0327dc21a4526",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "148b68de534a0ea513e3c3a8a5f0327dc21a4526",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "2fac1411c9a2d740405664c39eb6fbbc7b6ddbb2",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "312068b0e2b8743cc2bcf52bcde0180cec6f07ff",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "75d576f1e708422553bcd1d5f908a8027bda4364",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "c42dc1a0d375442acff79e104382275c1cc24ee3",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "75d576f1e708422553bcd1d5f908a8027bda4364",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "efe22a19d2e511ae49a6b4ce13607936702705dd",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "8c35005bd73c474f3c7bbc08eaee4c9357d274cc",
    "pipeline": "master"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "1687",
    "commit-sha": "d71795da91e5205096bc9725f095ff0b5c5500ed",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "800",
    "commit-sha": "8c35005bd73c474f3c7bbc08eaee4c9357d274cc",
    "pipeline": "master"
  }
]
```

**Review by abhijitherekar — APPROVED** [review]
LGTM.

**Pull request merged**
