### PR TITLE
Fix the included network validation.

### PR DESCRIPTION
**Pull request by abhijitherekar**
## Description

Rever the included network validation in UDP networks.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "udp-multi",
    "component": "gaia",
    "pr-id": "615",
    "commit-sha": "a3a1cd95dba06408a6c6430bd6437609be737dbd",
    "pipeline": "master"
  },
  {
    "project": "udp-multi",
    "component": "backend",
    "pr-id": "1048",
    "commit-sha": "bc112c679c18a818e46cd624dd7011b86709bd76",
    "pipeline": "master"
  },
  {
    "project": "udp-multi",
    "component": "apotests",
    "pr-id": "3169",
    "commit-sha": "401eedf1baddeba2c44ae9cacbe63eba78b11176",
    "pipeline": "master"
  }
]
```

**Review by brianonn — APPROVED** [review]
lgtm

**Review by brianonn — APPROVED** [review]
lgtm

**Review by brianonn — APPROVED** [review]
still lgtm

**Review by brianonn — APPROVED** [review]
Added SSO to my ssh key.. can I approve it now?

**Review by philipatl — APPROVED** [review]

**Pull request merged**
