### PR TITLE
Add validations that only east/west graphs when VPC is provided

### PR DESCRIPTION
**Pull request by dstiliadis**
Add validations that mandates that a VPC must be provided for all the east/west graph calculations.

### CODE REVIEW

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d4326de16465b3b677256afed6aa40995e01c50d",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "1f68323c70464aab24c9033056f1e8f4ee9dff55",
    "pipeline": "master"
  }
]
```

**Comment by zhaolanbao** [comment]
吴佳莹18016464175 徐汇

发自我的iPhone

在 2021年7月8日，06:55，Dimitri Stiliadis ***@***.***> 写道：

﻿

/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0

[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d61961d9dc5a0fb1b26c3f1ad7f743daac6313f0",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "7437241abbea93802d42cd7bb56c81a6b277be3a",
    "pipeline": "master"
  }
]

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "east-west",
    "component": "gaia",
    "pr-id": "682",
    "commit-sha": "d4326de16465b3b677256afed6aa40995e01c50d",
    "pipeline": "master"
  },
  {
    "project": "east-west",
    "component": "backend",
    "pr-id": "1267",
    "commit-sha": "b19f1e8d70660bb615c812090cd3f3984fed70f4",
    "pipeline": "master"
  }
]
```

**Pull request merged**
