### PR TITLE
severity omit empty

### PR DESCRIPTION
**Pull request by vjuux**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alarms",
    "component": "backend",
    "pr-id": "1809",
    "commit-sha": "edee27374f3840a89e6457c6be876a9ececc5aee",
    "pipeline": "master"
  },
  {
    "project": "alarms",
    "component": "gaia",
    "pr-id": "823",
    "commit-sha": "d3b7f05d30cbeb08dc6ce10f7dde306d295d803d",
    "pipeline": "master"
  }
]
```

**Comment by mloo3** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alarms",
    "component": "gaia",
    "pr-id": "823",
    "commit-sha": "8d2e8a96fd2b784dd0eb8d40972e795d03d3f820",
    "pipeline": "master"
  }
]
```

**Comment by vjuux** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alarms-severity",
    "component": "backend",
    "pr-id": "1813",
    "commit-sha": "5ed0d8c9d5f518cda7a366d219ff492f16e5cc12",
    "pipeline": "master"
  },
  {
    "project": "alarms-severity",
    "component": "gaia",
    "pr-id": "823",
    "commit-sha": "8d2e8a96fd2b784dd0eb8d40972e795d03d3f820",
    "pipeline": "master"
  }
]
```

**Review by ericrpowers — COMMENTED** [review]
I am curious how this would react with existing alarms that do not have this defined. Will they be able to update their occurrences field still or will it break on POST/PUT?

Otherwise, LGTM.

**Review by ericrpowers — APPROVED** [review]

**Pull request merged**
