### PR TITLE
Add ID to namespaceType

### PR DESCRIPTION
**Pull request by vjuux**
Currently there is no way to get the ID of current namespace from UI.

### CODE REVIEW

**Comment by vjuux** [comment]
Not quite certain if should be using `@identifiable-stored` in this case or create a separate property `namespaceID`.

**Comment by vjuux** [comment]
Also, would it make sense to replace multiple proxy endpoints `/tagprefixes`, `/defaultenforcerversion`, `/namespacetypes` that are returning individual properties of namespace with just one that would return the current namespace by `x-namespace` header provided.

**Comment by t00f** [comment]
We should not use `@identifiable-stored` but rather have a plain property `namespaceID` as the `ID` would represents the identifier of the NamespaceType object and NamespaceType is not a real object.

This property should be `readonly`.

I would like to keep multiple proxy APIs so it is easier to manage the authorizations for each of them. However, we can add the `namespaceID` in all the namespace proxy apis to be consistent, and I am sure it will be useful in the future too.

Also, we need some additional changes in the backend. It should be fairly straightforward though. Can you work with @ericrpowers ?

**Comment by vjuux** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "test-namespacetypes",
    "component": "backend",
    "pr-id": "1206",
    "commit-sha": "0838d2763f82c77ebb33375646b25e817220527e",
    "pipeline": "master"
  },
  {
    "project": "test-namespacetypes",
    "component": "gaia",
    "pr-id": "660",
    "commit-sha": "eb23a2ac6eb2c0d195f260969e02c94c617da275",
    "pipeline": "master"
  }
]
```

**Comment by vjuux** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "test-namespacetypes",
    "component": "gaia",
    "pr-id": "660",
    "commit-sha": "eb23a2ac6eb2c0d195f260969e02c94c617da275",
    "pipeline": "master"
  },
  {
    "project": "test-namespacetypes",
    "component": "backend",
    "pr-id": "1206",
    "commit-sha": "a430e950d83cfd662b465f23447655bb608ec4cb",
    "pipeline": "master"
  }
]
```

**Comment by vjuux** [comment]
Closing this in favor of `/putrafficactions`

**Pull request closed without merging**
