### PR TITLE
fix: gaia changes for Azure path

### PR DESCRIPTION
**Pull request by rramalinga**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-inbound-path",
    "component": "gaia",
    "pr-id": "774",
    "commit-sha": "a25cc7056773a536f22e6a14a22c1b6a1e92d410",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-inbound-path",
    "component": "backend",
    "pr-id": "1577",
    "commit-sha": "2a8ab06a41df3a27cfecef4300231192221d810f",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-inbound-path",
    "component": "gaia",
    "pr-id": "774",
    "commit-sha": "a25cc7056773a536f22e6a14a22c1b6a1e92d410",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-inbound-path",
    "component": "backend",
    "pr-id": "1577",
    "commit-sha": "d8c8ea307375760d67f92d1e3b81ca5d8a260de2",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-inbound-path",
    "component": "gaia",
    "pr-id": "774",
    "commit-sha": "a25cc7056773a536f22e6a14a22c1b6a1e92d410",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-inbound-path",
    "component": "backend",
    "pr-id": "1577",
    "commit-sha": "8e6f825edb931922c4396d2f2f4246dac95f4924",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-inbound-path",
    "component": "gaia",
    "pr-id": "774",
    "commit-sha": "a25cc7056773a536f22e6a14a22c1b6a1e92d410",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-inbound-path",
    "component": "backend",
    "pr-id": "1577",
    "commit-sha": "743503dd1175b73e5c378706342778c325336d5a",
    "pipeline": "master"
  }
]
```

**Review by abhijitherekar — APPROVED** [review]
LGTM

**Pull request merged**
