### PR TITLE
New: Enforcer default behavior property for namespace

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
We will be transitioning to having enforcer adjust its default behavior based on the namespace property `enforcerDefaultBehavior`. This is the first step in adding the property and the proxy API to manage it.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcer-default-behavior",
    "component": "backend",
    "pr-id": "938",
    "commit-sha": "b6daac145d3b822a8811f409571ba593eecc7b4a",
    "pipeline": "master"
  },
  {
    "project": "enforcer-default-behavior",
    "component": "gaia",
    "pr-id": "578",
    "commit-sha": "15211b01962f9057841e181f85b6ac496763da6a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "enforcer-default-behavior",
    "component": "backend",
    "pr-id": "938",
    "commit-sha": "b6daac145d3b822a8811f409571ba593eecc7b4a",
    "pipeline": "master"
  },
  {
    "project": "enforcer-default-behavior",
    "component": "gaia",
    "pr-id": "578",
    "commit-sha": "15211b01962f9057841e181f85b6ac496763da6a",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]
Looks good to me, thanks @ericrpowers!

@mheese @dstiliadis @primalmotion please have a quick look before we move forward. I'll merge this by EOD otherwise

**Review by primalmotion — APPROVED** [review]

**Comment by ericrpowers** [comment]
Closing in favor of merging work into https://github.com/PaloAltoNetworks/gaia/pull/577

**Pull request closed without merging**
