### PR TITLE
Add effective action to cloud network query

### PR DESCRIPTION
**Pull request by dstiliadis**
Adds the effective action parameter in cloud query and replaces the previous unreachable parameters.

### CODE REVIEW

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "fc9156efd7df0beec0905d1493b22965d415c2e9",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "00b21defa2fac462127f1287c11c474338866daf",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "addb57572994128719d3d7eebd455d7cbbb59fa3",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "a97c6903e94b35c6ebbb4bc014bca3a7dc319190",
    "pipeline": "master"
  }
]
```

**Review by jping0929 — APPROVED** [review]
LGTM 👍

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "9efb6c5acc502c322c4db65c2debb5e5b69ff5c3",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "d13bd8cd4cbdae5f76551f7eca7c189216db7046",
    "pipeline": "master"
  }
]
```

**Comment by dstiliadis** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "rql-effective-action",
    "component": "backend",
    "pr-id": "1195",
    "commit-sha": "fe2e5a256335e5ee02461af45417413d70c5153d",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "prismacloud",
    "pr-id": "36",
    "commit-sha": "e8a083e8b91c33f2ab486337996c17a0911d5015",
    "pipeline": "master"
  },
  {
    "project": "rql-effective-action",
    "component": "gaia",
    "pr-id": "655",
    "commit-sha": "7d637ac6b2c0c39e1433d1ab115fd0d4e989dd57",
    "pipeline": "master"
  }
]
```

**Pull request merged**
