### PR TITLE
Bugfix/meteor: formalize possible enum values for GraphNode type

### PR DESCRIPTION
**Pull request by malkhamis-panw**
The enum values added in this PR are the same for ProcessingUnit.Type enum values. It was found out that they were loosely used when converting a ProcessingUnit.Type to a GraphNode.Type... This PR is not meant to fix the abstraction, but to enhance safety when said abstraction is used. It also ensures that no changes at the UI side is necessary. For more information, see [CNS-3997](https://redlock.atlassian.net/browse/CNS-3997) and [this sister PR](https://git.scm.prismacloud.io/prismacloud/pcn/backend/-/merge_requests/1507)

### CODE REVIEW

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "gaia",
    "pr-id": "753",
    "commit-sha": "60be9756d3532afb68f7ec666a765cbd10de0fd0",
    "pipeline": "master"
  },
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "backend",
    "pr-id": "1507",
    "commit-sha": "382fc0fdb0a6535a7c1a1793d8882276fba643f2",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "gaia",
    "pr-id": "753",
    "commit-sha": "60be9756d3532afb68f7ec666a765cbd10de0fd0",
    "pipeline": "master"
  },
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "backend",
    "pr-id": "1507",
    "commit-sha": "616c68f302928c75ca98362542817e0d55dfd91c",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "gaia",
    "pr-id": "753",
    "commit-sha": "3af67d844a54469cd6ca06ec158ab7586466d82f",
    "pipeline": "master"
  },
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "backend",
    "pr-id": "1507",
    "commit-sha": "c080e05cdee9721e426710cff00398904ab29c5c",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "backend",
    "pr-id": "1507",
    "commit-sha": "6bfc9726977c5a358883ea9c6b50562756a6688f",
    "pipeline": "master"
  },
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "gaia",
    "pr-id": "753",
    "commit-sha": "3af67d844a54469cd6ca06ec158ab7586466d82f",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "gaia",
    "pr-id": "753",
    "commit-sha": "3af67d844a54469cd6ca06ec158ab7586466d82f",
    "pipeline": "master"
  },
  {
    "project": "bugfix-meteor-dangerous-cast",
    "component": "backend",
    "pr-id": "1507",
    "commit-sha": "6bfc9726977c5a358883ea9c6b50562756a6688f",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
