### PR TITLE
add external network id to flow report

### PR DESCRIPTION
**Pull request by philipatl**
## Description

add `SourceExternalNetworkID` and `DestinationExternalNetworkID` to flow reports

## Motivation and Context

CNS-4295
- enforcer will report the closest external network match for flow reports with no policy match

## How Has This Been Tested?

85% unit test coverage

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by primalmotion — APPROVED** [review]

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "8526753ad3e202f73c733e7d92891c483a66e554",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "f6176fc0794f65c8b4c0884387c6841f992f6d0d",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "cc4c176b6818509c90ead1ed97f5dec1d8770b2e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "cc4c176b6818509c90ead1ed97f5dec1d8770b2e",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "cc4c176b6818509c90ead1ed97f5dec1d8770b2e",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "476125f7460f7b32bcd2154284c9433137bc5243",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "7d4b409364fb083c5d922a75039e57398d8f35a5",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "71d322b8d82488fce04fa8ed96a26e2292b70d6a",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "87e494c778fc4500401907ff206ed708a8b5bfe8",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "912f55e49323dc2f9c2671418552c202752f4db2",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "a1b2b26e0711a1ec8e6e5eeec261613f6bf3b856",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "a1b2b26e0711a1ec8e6e5eeec261613f6bf3b856",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "a836c82b61c168d1888503027a6de8ffd8416920",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "a836c82b61c168d1888503027a6de8ffd8416920",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "a836c82b61c168d1888503027a6de8ffd8416920",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "53c3b57441d3796c4c6f012d8e3c820dfff491f2",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "53c3b57441d3796c4c6f012d8e3c820dfff491f2",
    "pipeline": "master"
  }
]
```

**Comment by philipatl** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "extnet-somewhere",
    "component": "enforcerd",
    "pr-id": "2703",
    "commit-sha": "b46dba688b2818e6aa74bd4375cea1a4abf96a56",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "gaia",
    "pr-id": "767",
    "commit-sha": "67aa28f52cfa099367136276683aa03f38f954bc",
    "pipeline": "master"
  },
  {
    "project": "extnet-somewhere",
    "component": "backend",
    "pr-id": "1564",
    "commit-sha": "63c09faf942b4ca4efcbd73b8de43eac32db0aa1",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
