### PR TITLE
Bugfix: prevent duplicate expressions in NetRuleSetPolicy's subject

### PR DESCRIPTION
**Pull request by malkhamis-panw**
This PR also make the first letter of error messages uppercase for consistency.

Reference JIRA tickets: [CNS-2829](https://redlock.atlassian.net/browse/CNS-2829?atlOrigin=eyJpIjoiNGQ1ZWNjYjU2MjFiNGM3ODllZjBmOTI5Mzg0OGMzOTgiLCJwIjoiaiJ9) and [CNS-2830](https://redlock.atlassian.net/browse/CNS-2830?atlOrigin=eyJpIjoiYjI5MGMwNGM1MmNkNDFkMmIwMDg2ZGQ1MGU3NzM3NTkiLCJwIjoiaiJ9)

### CODE REVIEW

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "netrulesetpolicy-validation",
    "component": "backend",
    "pr-id": "1297",
    "commit-sha": "79504183af4e62ae2581de3bbf8fa659ff2a80a9",
    "pipeline": "master"
  },
  {
    "project": "netrulesetpolicy-validation",
    "component": "gaia",
    "pr-id": "687",
    "commit-sha": "4465ce0f63841df44fc95f8dc22ab8e125d36572",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "netrulesetpolicy-validation",
    "component": "backend",
    "pr-id": "1297",
    "commit-sha": "79504183af4e62ae2581de3bbf8fa659ff2a80a9",
    "pipeline": "master"
  },
  {
    "project": "netrulesetpolicy-validation",
    "component": "gaia",
    "pr-id": "687",
    "commit-sha": "4465ce0f63841df44fc95f8dc22ab8e125d36572",
    "pipeline": "master"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "netrulesetpolicy-validation",
    "component": "gaia",
    "pr-id": "687",
    "commit-sha": "4465ce0f63841df44fc95f8dc22ab8e125d36572",
    "pipeline": "master"
  },
  {
    "project": "netrulesetpolicy-validation",
    "component": "backend",
    "pr-id": "1297",
    "commit-sha": "79504183af4e62ae2581de3bbf8fa659ff2a80a9",
    "pipeline": "master"
  }
]
```

**Review by aaslamin — APPROVED** [review]
Looks good to me 👍 

Would be nice to have an integration test on the backend whenever you have time to cover the e2e validation to minimize unintentional regressions.

**Review by t00f — APPROVED** [review]

**Review by aaslamin — APPROVED** [review]

**Pull request merged**
