### PR TITLE
added PCFW needed properties for endpoints

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "889",
    "commit-sha": "98cf08e096bd64b9bf08c7e4184c5b65bf33e46d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "139",
    "commit-sha": "c5795577c209092aabec3b65fcc8d9a7d1470eac",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "889",
    "commit-sha": "98cf08e096bd64b9bf08c7e4184c5b65bf33e46d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "139",
    "commit-sha": "09ac8043f76850eab68358e0d9bfe5a1463b1036",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "889",
    "commit-sha": "98cf08e096bd64b9bf08c7e4184c5b65bf33e46d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "139",
    "commit-sha": "09ac8043f76850eab68358e0d9bfe5a1463b1036",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "889",
    "commit-sha": "0f9569446c02d4bb8d7fd70f6d50943f310f5ddb",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "139",
    "commit-sha": "09ac8043f76850eab68358e0d9bfe5a1463b1036",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Review by sibicramesh — APPROVED** [review]

**Review by t00f — APPROVED** [review]

**Pull request merged**
