### PR TITLE
Add tags field to cloudalertrecord spec.

### PR DESCRIPTION
**Pull request by ayliao**
## Description

Adding a Tags field to cloudalertrecord

## Motivation and Context

This is needed because we need to be sending tags for the resource as well as per https://redlock.atlassian.net/browse/PCSUP-11923

## How Has This Been Tested?

Tested end to end with the other associated MRs 

https://git.scm.prismacloud.io/prismacloud/pcn/pccnabackend/-/merge_requests/16
https://git.scm.prismacloud.io/prismacloud/pcn/prismacloud/-/merge_requests/107

## Screenshots (if appropriate)

See https://git.scm.prismacloud.io/prismacloud/pcn/pccnabackend/-/merge_requests/16

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "b1b0c1e67eee5a3940103f34eece4b5c03b4b238",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "119c04b051761f908c56e8fefe58d5b808e8cf02",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "f168a637454cf22735b79eebd5e19189e9874e57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "cc37fd61061c243b2864de66a13cc0ff6df58f21",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "63ca8ccf6192e229f8e3d492e413269ac7c0a00d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "f168a637454cf22735b79eebd5e19189e9874e57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "ba773c6bb0afccc94fc6726649a9be64de9c993b",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "b4e690b0f41b966be55324556979021a4e784769",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "f168a637454cf22735b79eebd5e19189e9874e57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "7c3432f40c3e9fcaae8597650762fcb350f18f45",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "5667a46fe91621a118c7ec6a66ffeb3d65d33a7e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "9c5cdaaa721ca0c682c6df416b2705f4a2447037",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "b516b1eedfc21d846ab4dd99b60c942821443b3a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "b516b1eedfc21d846ab4dd99b60c942821443b3a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "b516b1eedfc21d846ab4dd99b60c942821443b3a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "ccb3e1278a20110265d5a2069522b6a8afa9228c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "ccb3e1278a20110265d5a2069522b6a8afa9228c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "2e628d4ff62cff0d6060c844b68290a4aa07a219",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "403370ec06fd951c55ec7b695a5c33316562b624",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Review by malkhamis-panw — APPROVED** [review]

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "273de3c116428587d2ef844a2745d22cfeaa2652",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "3145753ea07a160a318ca767b52f08f6308d7ee0",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "92f398476f403b81adbd441e5d13dc2c48ff161e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "66565fe62857bfdd80d9fcf53f2d28bf33fb89c4",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "11d91966d353476a611ad18eac09e5b1d7c90abc",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by ayliao** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "16",
    "commit-sha": "8d69fc54f57177a2c3684db0fd6e39e98f7f3d51",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "877",
    "commit-sha": "bbaadd46d98b5c87f71c03f5014e93e072af39db",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "107",
    "commit-sha": "bc1afc68262ba4371f72b2803074a0e64d5d4726",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Pull request merged**
