### PR TITLE
New: defaultAcceptedFlows and defaultRejectedFlows

### PR DESCRIPTION
**Pull request by jping0929**

### CODE REVIEW

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graphedge",
    "component": "backend",
    "pr-id": "1252",
    "commit-sha": "af56eb8ff3896152146a79bfb4c1ab5c83f201fd",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "gaia",
    "pr-id": "674",
    "commit-sha": "60dadfdc8c0ce598797503ec4da2983b2f778291",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graphedge",
    "component": "backend",
    "pr-id": "1252",
    "commit-sha": "2d1de0cd66e9e88dfa892f7d7405279923ce71d0",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "gaia",
    "pr-id": "674",
    "commit-sha": "60dadfdc8c0ce598797503ec4da2983b2f778291",
    "pipeline": "master"
  }
]
```

**Comment by primalmotion** [comment]
what's the status of this? If outdated, please close

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graphedge",
    "component": "backend",
    "pr-id": "1252",
    "commit-sha": "bb9836b8e5ec1f43a8ca1c6b7cc983d77badbd4b",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "gaia",
    "pr-id": "674",
    "commit-sha": "7556db28377cd9739d08d581b8e3d64934b01042",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graphedge",
    "component": "backend",
    "pr-id": "1252",
    "commit-sha": "c8d6c8882bbb29c629779193b0d9fb15e23cbead",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "apotests",
    "pr-id": "3526",
    "commit-sha": "59f711b16e8ac706daea1ce46781aae464ed4c89",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "gaia",
    "pr-id": "674",
    "commit-sha": "379d0ed122ffc0fd65906b54158f9158717828b9",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "graphedge",
    "component": "backend",
    "pr-id": "1252",
    "commit-sha": "006316d8f6e95c2ebf352f5d2de321cd499be83f",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "apotests",
    "pr-id": "3526",
    "commit-sha": "59f711b16e8ac706daea1ce46781aae464ed4c89",
    "pipeline": "master"
  },
  {
    "project": "graphedge",
    "component": "gaia",
    "pr-id": "674",
    "commit-sha": "379d0ed122ffc0fd65906b54158f9158717828b9",
    "pipeline": "master"
  }
]
```

**Pull request merged**
