### PR TITLE
updated naming for K8s filters

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "k8s-filter",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "k8s-filter",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "4ff458c0",
    "commit-full-sha": "4ff458c0d3787be0bac327f8014a305c02e75c57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "af1517ff",
    "commit-full-sha": "af1517ff8cec01d0f9c9729ea44c7ea61a034e43",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "k8s-filter",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "4ff458c0",
    "commit-full-sha": "4ff458c0d3787be0bac327f8014a305c02e75c57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "000615ae",
    "commit-full-sha": "000615ae6efc3a30b7710576d9760f1d0d92eaa3",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "k8s-filter",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "k8s-filter",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "k8s-filter",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "4ff458c0",
    "commit-full-sha": "4ff458c0d3787be0bac327f8014a305c02e75c57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "2545bf03",
    "commit-full-sha": "2545bf03c9f8b78da9de5dddbacb376ba7655ffd",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "k8s-filter",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "k8s-filter",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "4ff458c0",
    "commit-full-sha": "4ff458c0d3787be0bac327f8014a305c02e75c57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "k8s-filter",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "503c2f76",
    "commit-full-sha": "503c2f76e56289a859261f549d9cd1027e793274",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "4ff458c0",
    "commit-full-sha": "4ff458c0d3787be0bac327f8014a305c02e75c57",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "503c2f76",
    "commit-full-sha": "503c2f76e56289a859261f549d9cd1027e793274",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by itsai220** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "734c0a1e",
    "commit-full-sha": "734c0a1e69415b77e8483d884b01ac68dcd363d7",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "503c2f76",
    "commit-full-sha": "503c2f76e56289a859261f549d9cd1027e793274",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by itsai220** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "734c0a1e",
    "commit-full-sha": "734c0a1e69415b77e8483d884b01ac68dcd363d7",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "503c2f76",
    "commit-full-sha": "503c2f76e56289a859261f549d9cd1027e793274",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "52e34d17",
    "commit-full-sha": "52e34d17c5b7393d7ce00acb90ac6f5ec709ceed",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "503c2f76",
    "commit-full-sha": "503c2f76e56289a859261f549d9cd1027e793274",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2168",
    "commit-sha": "52e34d17",
    "commit-full-sha": "52e34d17c5b7393d7ce00acb90ac6f5ec709ceed",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "135",
    "commit-sha": "503c2f76",
    "commit-full-sha": "503c2f76e56289a859261f549d9cd1027e793274",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "940",
    "commit-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "commit-full-sha": "f4add5d26f695b1bc9eae0a27810f860967f7b0c",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "494",
    "commit-sha": "04fcabdd",
    "commit-full-sha": "04fcabddbfe1ba11fd4dc38f7344e3e483c6341c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Pull request merged**
