### PR TITLE
Terminology updates

### PR DESCRIPTION
**Pull request by emanic**
Changes terms: control plane, defender to new equivalents.
No functional impact, this is just for documentation.md

### CODE REVIEW

**Comment by primalmotion** [comment]
conflicts

**Comment by emanic** [comment]
@primalmotion conflicts resolved

**Comment by t00f** [comment]
@emanic seems like there is another conflict, please resync and let me know so we can move forward with your changes

**Comment by emanic** [comment]
@t00f OK thanks. Also, there is a conflict in `go.sum` that I'm not sure how to resolve, wasn't sure which change would be preferred there.

**Comment by emanic** [comment]
@t00f nvm, I just selected the go.sum from my branch.

**Pull request merged**
