### PR TITLE
Aws lb path

### PR DESCRIPTION
**Pull request by abhijitherekar**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "14f021f25455baa0166013e6b1ec30e6f9f8922b",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "bbff9390e679a426798d2741e5a26babd34994f0",
    "pipeline": "master"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "121dd01a55eac72f485db5af76bbca14ad1dc7cb",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "0cb901a0efee5aeb324a8bcca710de4a4e5ba7ad",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "7ed18b07e867786f7771d83cbb48b6623f0ad846",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "7ed18b07e867786f7771d83cbb48b6623f0ad846",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "7ed18b07e867786f7771d83cbb48b6623f0ad846",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "aws-lb",
    "component": "gaia",
    "pr-id": "744",
    "commit-sha": "b892b4ddb419d6196523a2f416d2e7775909fde8",
    "pipeline": "master"
  },
  {
    "project": "aws-lb",
    "component": "backend",
    "pr-id": "1461",
    "commit-sha": "f372b94c960daee1b74217032f4f5a8311acb3a8",
    "pipeline": "master"
  }
]
```

**Pull request merged**
