### PR TITLE
Cloud graph result using mongo gridFS

### PR DESCRIPTION
**Pull request by abhijitherekar**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "194f3d3262d17f25498a33e89215e495ba5f017b",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "711",
    "commit-sha": "06110a4c380524a07b10f4c423c6f01520b22ab4",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "76f34ce59dbbc30a1052882dc805e44a02128c46",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "711",
    "commit-sha": "06110a4c380524a07b10f4c423c6f01520b22ab4",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "0b55e0243b16239054ec10d125cea7ea84293808",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "711",
    "commit-sha": "06110a4c380524a07b10f4c423c6f01520b22ab4",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "711",
    "commit-sha": "06110a4c380524a07b10f4c423c6f01520b22ab4",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "ff210d892c4c84789f32febc415adb0b3eedc00b",
    "pipeline": "master"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Pull request merged**
