### PR TITLE
Added new cloud node type for auto scaling group

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Description
https://redlock.atlassian.net/browse/CNS-6308

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "1a5ea72778738a80e46cdaf56ba27e802d8a8648",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "1ce3db4a03035b552ec591487e1520160e9359d4",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "1a5ea72778738a80e46cdaf56ba27e802d8a8648",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "1ce3db4a03035b552ec591487e1520160e9359d4",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "42a19515495faf7b87e4df5a2c936bdaf7f8e760",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "93aee1a483ef541510bf766e8825c3d23ff6cc4f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "42a19515495faf7b87e4df5a2c936bdaf7f8e760",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "f5b2e3151b6f79ac326aa5a8cd97607eedd2071a",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "65d58b9335d7de95d9e6f59e4b3465f87cfbd1e7",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "379795587693f7275e93dee612cfdb7c939cf3db",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "d1dee9fd1201e22db4259bc5937c916a6e0ffcb0",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "409586d718c4e4bc1d60cb540569246dd94466e6",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "d1dee9fd1201e22db4259bc5937c916a6e0ffcb0",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "612ef607209da82ae326d1201b3658b0c6faaa39",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "d1dee9fd1201e22db4259bc5937c916a6e0ffcb0",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "612ef607209da82ae326d1201b3658b0c6faaa39",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "887",
    "commit-sha": "d1dee9fd1201e22db4259bc5937c916a6e0ffcb0",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "120",
    "commit-sha": "9e69e0b4b4aa5f2230b60cd4776f8360bb598b45",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Review by sibicramesh — APPROVED** [review]

**Review by t00f — APPROVED** [review]

**Pull request merged**
