### PR TITLE
Add ASG support for Azure

### PR DESCRIPTION
**Pull request by jping0929**

### CODE REVIEW

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "nic-asg",
    "component": "backend",
    "pr-id": "1716",
    "commit-sha": "ab9cb5173acf82b48401bb42f2bdad26d32c9a2e",
    "pipeline": "master"
  },
  {
    "project": "nic-asg",
    "component": "gaia",
    "pr-id": "811",
    "commit-sha": "cfffd81ed5189033134dae8c8142eb8447384eb1",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "nic-asg",
    "component": "backend",
    "pr-id": "1716",
    "commit-sha": "ab9cb5173acf82b48401bb42f2bdad26d32c9a2e",
    "pipeline": "master"
  },
  {
    "project": "nic-asg",
    "component": "gaia",
    "pr-id": "811",
    "commit-sha": "961885d5869ead3dff35bf469932f9979272dafa",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "nic-asg",
    "component": "backend",
    "pr-id": "1716",
    "commit-sha": "e658eb2f4dd2f26936ba94adc51ef9919f01ad2e",
    "pipeline": "master"
  },
  {
    "project": "nic-asg",
    "component": "gaia",
    "pr-id": "811",
    "commit-sha": "8f0ac89b865cadd576e82397daa266a683ee8b0f",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "nic-asg",
    "component": "gaia",
    "pr-id": "811",
    "commit-sha": "8f0ac89b865cadd576e82397daa266a683ee8b0f",
    "pipeline": "master"
  },
  {
    "project": "nic-asg",
    "component": "backend",
    "pr-id": "1716",
    "commit-sha": "0c983f19550e689e8db9dd61d50a7c5b82340acf",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "nic-asg",
    "component": "backend",
    "pr-id": "1745",
    "commit-sha": "e2bad445415739d98f6495b9e0b9492a670b5011",
    "pipeline": "master"
  },
  {
    "project": "nic-asg",
    "component": "gaia",
    "pr-id": "811",
    "commit-sha": "00c908243d5a759858c1cdcb005428ef2b9f47ff",
    "pipeline": "master"
  }
]
```

**Review by abhijitherekar — APPROVED** [review]

**Pull request merged**
