### PR TITLE
Update: Make suggestedpolicy API filterable

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
Per https://redlock.atlassian.net/browse/CNS-3848 we want a want to filter on suggestedpolicy API. This will expose permission for such

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "suggestedpolicy-allow-query",
    "component": "backend",
    "pr-id": "1567",
    "commit-sha": "a5c8edaee169afa0f3afc0eb5ec3d18cf12cc479",
    "pipeline": "master"
  },
  {
    "project": "suggestedpolicy-allow-query",
    "component": "gaia",
    "pr-id": "770",
    "commit-sha": "f4f00d3c43a0e7c22059001ee0146e8db9ae7a52",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "suggestedpolicy-allow-query",
    "component": "backend",
    "pr-id": "1567",
    "commit-sha": "2d14537b71e613cd87faf97549df57ece497bfec",
    "pipeline": "master"
  },
  {
    "project": "suggestedpolicy-allow-query",
    "component": "gaia",
    "pr-id": "770",
    "commit-sha": "f4f00d3c43a0e7c22059001ee0146e8db9ae7a52",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Review by t00f — APPROVED** [review]

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "suggestedpolicy-allow-query",
    "component": "backend",
    "pr-id": "1567",
    "commit-sha": "e2bdcc375ba099bf0f5911478e9a6d6717a6c488",
    "pipeline": "master"
  },
  {
    "project": "suggestedpolicy-allow-query",
    "component": "gaia",
    "pr-id": "770",
    "commit-sha": "b0a19493c816bdad6a9aac22c83bc470bb312ccf",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "suggestedpolicy-allow-query",
    "component": "gaia",
    "pr-id": "770",
    "commit-sha": "0a5ee7eb49e8e32b5b0341b72b29ad4af4ad6404",
    "pipeline": "master"
  },
  {
    "project": "suggestedpolicy-allow-query",
    "component": "backend",
    "pr-id": "1567",
    "commit-sha": "f0cbc244f838c3bb9c7016815910a21500f9736b",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
