### PR TITLE
neocna: gcpresource: consts for ComputeTargetHttp(s)Proxy

### PR DESCRIPTION
**Pull request by malkhamis-panw**

### CODE REVIEW

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "backend",
    "pr-id": "2014",
    "commit-sha": "68fabd5786bc7f7d3b19c1e133e8d68670b7819a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "gaia",
    "pr-id": "874",
    "commit-sha": "230c3dcd22a846e7a3562ab34f894a508078e216",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Review by t00f — APPROVED** [review]

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "backend",
    "pr-id": "2014",
    "commit-sha": "68fabd5786bc7f7d3b19c1e133e8d68670b7819a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "gaia",
    "pr-id": "874",
    "commit-sha": "230c3dcd22a846e7a3562ab34f894a508078e216",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "backend",
    "pr-id": "2014",
    "commit-sha": "e2743bf5f91f10bf1a476ed7cf63ca983e5551d7",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "gaia",
    "pr-id": "874",
    "commit-sha": "a1972767857bfce23d3a896fa97d654788d66e6b",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "backend",
    "pr-id": "2014",
    "commit-sha": "cb34a6741fedb1ae4ac34564030b88a000b126ab",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "neocna-gcp-targethttpproxy-model",
    "component": "gaia",
    "pr-id": "874",
    "commit-sha": "a1972767857bfce23d3a896fa97d654788d66e6b",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Pull request merged**
