### PR TITLE
Enforcer Testing latest Gaia for policy default actions

### PR DESCRIPTION
**Pull request by tillery-aporeto**

### CODE REVIEW

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "3777979f9a93e2f3bcd248817126811cae0caff3",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "13b00eee4278063ed7f6d70c03742116c1ead9d1",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "5b46b7d6a8c5a49a11837c7e85e086e6ec5d29ac",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "a073ae907c71b6ef2344fdfb4b536f51f440ee39",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "f2b36dd4672e50cc341523805a49265e2052c161",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "ebeece16960979ecb45d8ca48a65f01bc7da6819",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "855051aa4e4ca904614cd426769bd6ed53e29b2f",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "fe5154c3375ff98ccbcef23689b9f82e56279752",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "100ef14208fa12a852997b13bbb1d9c69b2d0d70",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "2776d82f166dc1775acd86dd67de6f7c7b89f6f7",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "4374f7814db94efde026fd34b8d7e932b9743635",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "da235f5ea6464fbb0808f1193ae75f2c32692590",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "98bb1b8204235d881f14a551221c38ac2710e5b0",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "234dc88b6a786ffa88004d40d67a54b2541971f8",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "d16afb954cc041866b2ee095e88c9abf2ec6ade8",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "141cc5bc5ed2e70121ca4579e8d1fc7cd5c1994a",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "6bdba66d701f08834bb70ef8e1b856ea49b3df2d",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "593",
    "commit-sha": "5b28a06f142eb27aaf55c69b1b2f40a3e57cc2b1",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "enforcerd",
    "pr-id": "2138",
    "commit-sha": "6bdba66d701f08834bb70ef8e1b856ea49b3df2d",
    "pipeline": "master"
  }
]
```

**Comment by primalmotion** [comment]
what's the status of this? If outdated, please close

**Pull request closed without merging**
