### PR TITLE
CNS-739: add support for "monotonic" shard key for the ingestion of reports

### PR DESCRIPTION
**Pull request by aaslamin**
This PR is identical to the work done in https://github.com/PaloAltoNetworks/gaia/pull/583, but instead removes `spread` and reuses `zHash` as they are both integers.

### CODE REVIEW

**Review by primalmotion — APPROVED** [review]
waaaaay better :)

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "a3f6056de38fb849b2658ec5c6196659b0c69818",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "af389a3be46a4bc99e1d8c3df1534ab62c9d4dfc",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "a3f6056de38fb849b2658ec5c6196659b0c69818",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "af389a3be46a4bc99e1d8c3df1534ab62c9d4dfc",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "a3f6056de38fb849b2658ec5c6196659b0c69818",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "c8977a5eccdee73096b7aa398e8feb7cac7aa3f8",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "a3f6056de38fb849b2658ec5c6196659b0c69818",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "a2a92c4962f0c815d73bbf5a9ffaafeea3d5461c",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "a3f6056de38fb849b2658ec5c6196659b0c69818",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "035fd8a05e059f58a8187a09ef9edef578dde50f",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "a3f6056de38fb849b2658ec5c6196659b0c69818",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "035fd8a05e059f58a8187a09ef9edef578dde50f",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "5c06776f9219f02b1739ecd9dd37a171cf95527e",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "0ec2a4a1a82df51f12b59d443cf2bd3148bc4d12",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "0ec2a4a1a82df51f12b59d443cf2bd3148bc4d12",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "5c06776f9219f02b1739ecd9dd37a171cf95527e",
    "pipeline": "master"
  }
]
```

**Comment by aaslamin** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "monotonic",
    "component": "gaia",
    "pr-id": "595",
    "commit-sha": "5c06776f9219f02b1739ecd9dd37a171cf95527e",
    "pipeline": "master"
  },
  {
    "project": "monotonic",
    "component": "backend",
    "pr-id": "968",
    "commit-sha": "0ec2a4a1a82df51f12b59d443cf2bd3148bc4d12",
    "pipeline": "master"
  }
]
```

**Pull request merged**
