### PR TITLE
fix: Alert aggregation

### PR DESCRIPTION
**Pull request by rramalinga**
## Description

For alert integration, creating endpoints for objects so that the feature can be tested without PC integration.

### CODE REVIEW

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "a23eb5b650131a1e22a267ca686f8fd70e36fd81",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "cf8cb0a3c321b20af19d75c9c400bb1c7ebbfd02",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "f6dd9bb64e181a2d5a70c0279e1e1b013e453ecc",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "86a33df94cd1e6de815b3109089a3c2d78900f37",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "ea43f0bdc624588d1e9bd7cfb464298e1aa11b64",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "aeefa477c281c7b37c4f76f9f1d0f4f081915c77",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "ea43f0bdc624588d1e9bd7cfb464298e1aa11b64",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "5aa30318545c0f728aa7189caa5a1f1bfc63a4ff",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "7df7b8e0a9278078000caf724f094699f3ac7673",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "f17704f95e13d314edacc0db73f9649d864c7358",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "7df7b8e0a9278078000caf724f094699f3ac7673",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "f17704f95e13d314edacc0db73f9649d864c7358",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "7df7b8e0a9278078000caf724f094699f3ac7673",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "0bb0453ecff75b88d087e8552c57cfa9d0be21ac",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "7df7b8e0a9278078000caf724f094699f3ac7673",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "101300b3d35f94bd5175f67463b541c041f9382d",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "d3641f020bd41674989f5185913722ad71afb633",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Review by dstiliadis — APPROVED** [review]

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "a4f4df67376dbdbfd0ec8d1990324fa6617771fc",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "d3641f020bd41674989f5185913722ad71afb633",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "cdf7f7d6a2853e3eb4781e9b875e2a14cd966f25",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "prismacloud",
    "pr-id": "53",
    "commit-sha": "d3641f020bd41674989f5185913722ad71afb633",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "alert-integ-phase-1",
    "component": "gaia",
    "pr-id": "700",
    "commit-sha": "26896e1f34c270880e02513ad5ab060ffd1891c0",
    "pipeline": "master"
  },
  {
    "project": "alert-integ-phase-1",
    "component": "backend",
    "pr-id": "1331",
    "commit-sha": "cd527701d17f08136a3fba7a981194d763a1bebf",
    "pipeline": "master"
  }
]
```

**Pull request merged**
