### PR TITLE
Update: Merge HostGroup and KubernetesClusterGroup into Group

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
We are moving to condense the two types of namespaces into one generic one. This is the start.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "merge-groups",
    "component": "backend",
    "pr-id": "955",
    "commit-sha": "168a87a3f926638d71e92746351769c2f5e48dc2",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "gaia",
    "pr-id": "585",
    "commit-sha": "76a4651d248d924baf3260124b9dde377045092a",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "clad",
    "pr-id": "1895",
    "commit-sha": "f823375686fbbfe2ccf64a1aaee86561be0b77cf",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "apotests",
    "pr-id": "3019",
    "commit-sha": "a8f21294301d2953922692efe5004672750b759c",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "apotests",
    "pr-id": "3019",
    "commit-sha": "3a0b8a4fc21df476733974f16d5a9c338a3cb392",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "585",
    "commit-sha": "76a4651d248d924baf3260124b9dde377045092a",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "merge-groups",
    "component": "apotests",
    "pr-id": "3019",
    "commit-sha": "d2cd937c0fe5428e16fb41012afa8493de9adbd8",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "backend",
    "pr-id": "955",
    "commit-sha": "b57a30277a533cb125aaad888d13de56c4f90d97",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "gaia",
    "pr-id": "585",
    "commit-sha": "b15c68f0369f2889028269d743c7f437f466dd8e",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "clad",
    "pr-id": "1895",
    "commit-sha": "f823375686fbbfe2ccf64a1aaee86561be0b77cf",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "merge-groups",
    "component": "backend",
    "pr-id": "955",
    "commit-sha": "f33d2ba7c7a76705c0205e17cd903ff2603ab5c8",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "gaia",
    "pr-id": "585",
    "commit-sha": "b15c68f0369f2889028269d743c7f437f466dd8e",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "clad",
    "pr-id": "1895",
    "commit-sha": "f823375686fbbfe2ccf64a1aaee86561be0b77cf",
    "pipeline": "master"
  },
  {
    "project": "merge-groups",
    "component": "apotests",
    "pr-id": "3019",
    "commit-sha": "d2cd937c0fe5428e16fb41012afa8493de9adbd8",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
