### PR TITLE
Update gaia model for RQL

### PR DESCRIPTION
**Pull request by jping0929**
- add time range parameter

### CODE REVIEW

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-ga",
    "component": "backend",
    "pr-id": "1022",
    "commit-sha": "ae58f9834c6181415ac9a7d945465a35acbb560e",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "cc5d6ee233bc659429149f4276737765db30f093",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-ga",
    "component": "backend",
    "pr-id": "1022",
    "commit-sha": "ae58f9834c6181415ac9a7d945465a35acbb560e",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "11fccd3eec9b0598728b22c09d05f5aa06cf0d49",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-ga",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "11fccd3eec9b0598728b22c09d05f5aa06cf0d49",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "backend",
    "pr-id": "1022",
    "commit-sha": "c01bcdd93aa2e551f713392c829986dec935d1db",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-ga",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "11fccd3eec9b0598728b22c09d05f5aa06cf0d49",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "backend",
    "pr-id": "1022",
    "commit-sha": "c03747ffd1eea206b14d3381211c2fe10efb15fa",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-ga",
    "component": "backend",
    "pr-id": "1022",
    "commit-sha": "c03747ffd1eea206b14d3381211c2fe10efb15fa",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "11fccd3eec9b0598728b22c09d05f5aa06cf0d49",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-authns",
    "component": "backend",
    "pr-id": "1029",
    "commit-sha": "348b6fae7f2cd1c5ad4cf36649db35a8d1a5c661",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "11fccd3eec9b0598728b22c09d05f5aa06cf0d49",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-ga",
    "component": "backend",
    "pr-id": "1022",
    "commit-sha": "c03747ffd1eea206b14d3381211c2fe10efb15fa",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "00b4642a0c2a62da5d6f4aafcb58fb91a8d72c63",
    "pipeline": "master"
  },
  {
    "project": "RQL-ga",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "11fccd3eec9b0598728b22c09d05f5aa06cf0d49",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-authns",
    "component": "backend",
    "pr-id": "1029",
    "commit-sha": "6c121f1a16ce41ca18c6468b4609f97247d24ef9",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "de14e731fd398d47df31d77397db3fb91ba099e4",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "ab71cb7850f97022146595311b5f8725edda3692",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
failed because "you have reached the pull rate limit"
Verified locally with `make lint`

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-authns",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "6dc0259adb3795503b56068328dca282fafc850a",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "backend",
    "pr-id": "1029",
    "commit-sha": "dc49df34aa0f0b485f956a2441f93f4347f3356e",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "22c1883902ca324c237efc6611703cb038177060",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-authns",
    "component": "backend",
    "pr-id": "1029",
    "commit-sha": "dc49df34aa0f0b485f956a2441f93f4347f3356e",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "6ff8f64152eb2135c604daa754ad9917c64bbdd8",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "6dc0259adb3795503b56068328dca282fafc850a",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-authns",
    "component": "backend",
    "pr-id": "1029",
    "commit-sha": "dc49df34aa0f0b485f956a2441f93f4347f3356e",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "6ff8f64152eb2135c604daa754ad9917c64bbdd8",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "6dc0259adb3795503b56068328dca282fafc850a",
    "pipeline": "master"
  }
]
```

**Comment by jping0929** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "RQL-authns",
    "component": "backend",
    "pr-id": "1029",
    "commit-sha": "ee69360769e111c3fbf7c3a235ed36c9054655fe",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "prismacloud",
    "pr-id": "5",
    "commit-sha": "6ff8f64152eb2135c604daa754ad9917c64bbdd8",
    "pipeline": "master"
  },
  {
    "project": "RQL-authns",
    "component": "gaia",
    "pr-id": "609",
    "commit-sha": "6dc0259adb3795503b56068328dca282fafc850a",
    "pipeline": "master"
  }
]
```

**Pull request merged**
