### PR TITLE
Add rendererVersion

### PR DESCRIPTION
**Pull request by t00f**

### CODE REVIEW

**Comment by t00f** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "e2c01bc43e0499c6beb2c7f379ad7aee9724e43b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "f0a50f7eb6c0f67484db1ca8c6426a8ba5b85828",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "75bbb04fc5c3517f482b221538505603a499591b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "e2c01bc43e0499c6beb2c7f379ad7aee9724e43b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "f0a50f7eb6c0f67484db1ca8c6426a8ba5b85828",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "e2c01bc43e0499c6beb2c7f379ad7aee9724e43b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "f0a50f7eb6c0f67484db1ca8c6426a8ba5b85828",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "849644c350525c8287f1427cb1a58534213bde58",
    "pipeline": "master"
  }
]
```

**Review by primalmotion — APPROVED** [review]

**Comment by primalmotion** [comment]
I don't think you need a ft here

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "849644c350525c8287f1427cb1a58534213bde58",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "e2c01bc43e0499c6beb2c7f379ad7aee9724e43b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "f0a50f7eb6c0f67484db1ca8c6426a8ba5b85828",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "e2c01bc43e0499c6beb2c7f379ad7aee9724e43b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "7b5e10a37c8804c2ca4087063e514edb585683f0",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "61fdbc53a1d0fcd7ccad3a19401f639d35750fa9",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "apotests",
    "pr-id": "3315",
    "commit-sha": "e96d53b5090370a4eb3d082fd418e3baf08ae517",
    "pipeline": "master"
  }
]
```

**Comment by Rohit4793** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "61fdbc53a1d0fcd7ccad3a19401f639d35750fa9",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "apotests",
    "pr-id": "3315",
    "commit-sha": "e96d53b5090370a4eb3d082fd418e3baf08ae517",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "e2c01bc43e0499c6beb2c7f379ad7aee9724e43b",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "7b5e10a37c8804c2ca4087063e514edb585683f0",
    "pipeline": "master"
  }
]
```

**Comment by t00f** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "7b5e10a37c8804c2ca4087063e514edb585683f0",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "61fdbc53a1d0fcd7ccad3a19401f639d35750fa9",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "apotests",
    "pr-id": "3315",
    "commit-sha": "e96d53b5090370a4eb3d082fd418e3baf08ae517",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "5f054c461b78eb0bbfdb861fc87d7dc9537385fd",
    "pipeline": "master"
  }
]
```

**Comment by tillery-aporeto** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "add_rendererversion",
    "component": "gaia",
    "pr-id": "640",
    "commit-sha": "5f054c461b78eb0bbfdb861fc87d7dc9537385fd",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "backend",
    "pr-id": "1146",
    "commit-sha": "7b5e10a37c8804c2ca4087063e514edb585683f0",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "underwater",
    "pr-id": "140",
    "commit-sha": "2db163b0cf019a9d6ca39303fa6a5f411fcdc3e4",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "enforcerd",
    "pr-id": "2387",
    "commit-sha": "3c534b3bc7500764ed84b9d261f13e1224d975a2",
    "pipeline": "master"
  },
  {
    "project": "add_rendererversion",
    "component": "apotests",
    "pr-id": "3315",
    "commit-sha": "f46057dca380b8f04291dda31a9c1ad5e33e20fa",
    "pipeline": "master"
  }
]
```

**Pull request merged**
