### PR TITLE
fix: Azure Outbound Path

### PR DESCRIPTION
**Pull request by rramalinga**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-outbound",
    "component": "gaia",
    "pr-id": "787",
    "commit-sha": "c3c6a6ebceb982b55f57c17c4720c11e4ba455ad",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "prismacloud",
    "pr-id": "80",
    "commit-sha": "293b1208875a226abd6798e1adca4058e1b461bb",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "backend",
    "pr-id": "1622",
    "commit-sha": "b64418d769f63f735c7f0389aa10903d2f84dfba",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-outbound",
    "component": "prismacloud",
    "pr-id": "80",
    "commit-sha": "293b1208875a226abd6798e1adca4058e1b461bb",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "backend",
    "pr-id": "1622",
    "commit-sha": "99d64b9b31f52374e2fe25ca344844a989fd556d",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "gaia",
    "pr-id": "787",
    "commit-sha": "c3c6a6ebceb982b55f57c17c4720c11e4ba455ad",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-outbound",
    "component": "backend",
    "pr-id": "1622",
    "commit-sha": "0dd478765e73bdf16c459804b3b4d7f2b0c70028",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "gaia",
    "pr-id": "787",
    "commit-sha": "c3c6a6ebceb982b55f57c17c4720c11e4ba455ad",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "prismacloud",
    "pr-id": "80",
    "commit-sha": "293b1208875a226abd6798e1adca4058e1b461bb",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-azure-outbound",
    "component": "prismacloud",
    "pr-id": "80",
    "commit-sha": "293b1208875a226abd6798e1adca4058e1b461bb",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "backend",
    "pr-id": "1622",
    "commit-sha": "a93a91f30a484ffa0ff1a75101ee1d8848e5e78e",
    "pipeline": "master"
  },
  {
    "project": "fix-azure-outbound",
    "component": "gaia",
    "pr-id": "787",
    "commit-sha": "c3c6a6ebceb982b55f57c17c4720c11e4ba455ad",
    "pipeline": "master"
  }
]
```

**Pull request merged**
