### PR TITLE
neocna/core: distributed flooding v0.3

### PR DESCRIPTION
**Pull request by malkhamis-panw**
These changes are needed so we can start multiple remote flooders in a single floodrpc request. In addition, the request param to request distributed flooding is removed.. the helm value should be sufficient

### CODE REVIEW

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "219",
    "commit-sha": "1e7159150710ef5b05c79aad5d39fadf46174cb1",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "1edc0a7ed5e30a8c206d6e2cb19ace3f474e644f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "8306557b2eadf192a671b213f5de29c23c143ead",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "beb429a233fad2314cd0b6646cee40b665665017",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "2e7b27f8da20a7153f3d6418b153c346b4f9c5d6",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "66218d0e95258973c39dc1049e93d862fb9ae65a",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "12fd29085a7ec40c6ca07da5a686cfe37460adb4",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "03dd2572ce069ba13c9ca7e6fdbf571cde86fe29",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by malkhamis-panw** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "pccnabackend",
    "pr-id": "251",
    "commit-sha": "85bd9d762bc8675a874ce3178beafb91902b4c67",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "904",
    "commit-sha": "9ec0d833493cf2e7c8ba7fa72897278b59746da5",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
