### PR TITLE
New: Namespace type for Tenant, Cloud Account and Group

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
Per https://redlock.atlassian.net/browse/CNS-77 we are looking to add a type to the namespace model to handle the following scenarios:
- `Default`: A universal namespace that is capable of all actions and views.
- `Tenant`: A namespace that houses a tenant.
- `CloudAccount`: A child namespace of a tenant that houses a cloud provider account.
- `Group`: A child namespace of a cloud account that houses a managed group.

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "namespace-type",
    "component": "backend",
    "pr-id": "888",
    "commit-sha": "bb17e72837269947dee85e3c8c920a4ada91392a",
    "pipeline": "master"
  },
  {
    "project": "namespace-type",
    "component": "gaia",
    "pr-id": "559",
    "commit-sha": "0f342aeb417c91205c7efb46d5b2afc981512b25",
    "pipeline": "master"
  }
]
```

**Review by t00f — CHANGES_REQUESTED** [review]
Instead of Group, can you add the following types:
* Host Group
* K8s Cluster Group
* K8s

Otherwise it looks good to me!

**Review by t00f — APPROVED** [review]
Ok it seems they are not sure... let's move forward!

**Review by primalmotion — APPROVED** [review]
L"g"tm

**Pull request merged**
