### PR TITLE
Findings new feature flags

### PR DESCRIPTION
**Pull request by sawyerawesome**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "6454acddaa5ffdebd343beefe140b8aac4368a30",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "9e894c9b96b0e1dcc97f416dccf8a5d5f9f17970",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "74034b1ab8d063df260eadefa67f10acae68d139",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "9e894c9b96b0e1dcc97f416dccf8a5d5f9f17970",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "74034b1ab8d063df260eadefa67f10acae68d139",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "32ef89c79a098613359c2599204fc8c80978fbe3",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "e36da72bee7a66b9ef0f5929326dbfb98dbfb052",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "9e894c9b96b0e1dcc97f416dccf8a5d5f9f17970",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "74034b1ab8d063df260eadefa67f10acae68d139",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "6164a599ebe1f0e6f368651e26c72ddc860102d5",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "c37f4c2d3b4156c02aba1832b63f6e526397ad6c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "766989b952324f5d50e4781298853d9a2377ceac",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "c37f4c2d3b4156c02aba1832b63f6e526397ad6c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "51484ff12dbf337fb9d1a8a2c78bc791d8df5e3f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "c37f4c2d3b4156c02aba1832b63f6e526397ad6c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "6f12ca917308e73da1a37284409f40346b81c277",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "c37f4c2d3b4156c02aba1832b63f6e526397ad6c",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "af9e9fa0539ed964ed7cd925b8f040c86d516632",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "d6bb1507c9530b3001ec58cf83419fab651adc6e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "a1be596f3f98f5af04e7790afb31cf3c21c14974",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "d6bb1507c9530b3001ec58cf83419fab651adc6e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "d6bb1507c9530b3001ec58cf83419fab651adc6e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "c4ef9fa95c5513aa37c673dc81043142649be1d4",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "b64d16d93a3f3450feeef958ae68853c85f04c6b",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "d6bb1507c9530b3001ec58cf83419fab651adc6e",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "7bd839feb011cbf01d9775efdfa0a861caa71f25",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "c6658652d2a98299e0c29b4b5cb7c0bd60b0b95a",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "bd8805aaa336386ba786c2466276a05080b6abc2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "915aba2859de148147ea26631dc685d059e2f0ca",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "da3e775034e230f35282f5cf933abdf799977ddf",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "cc682282ed35f9fd412c63b615e7748949e0036b",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "da3e775034e230f35282f5cf933abdf799977ddf",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "74878722fc64c429e8dc43eff27ee2f0ee641c2f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "da3e775034e230f35282f5cf933abdf799977ddf",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "da3e775034e230f35282f5cf933abdf799977ddf",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "74878722fc64c429e8dc43eff27ee2f0ee641c2f",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "cff193164024ade3df4618dbe1cd3eec6824b7ce",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "da3e775034e230f35282f5cf933abdf799977ddf",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "bd6abc61c6677051e9ba4ea5a563dadbe4eb93c2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "302e7491dc2c495cb1a8f4c5984cc8ed7e163663",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "932e7fb7e62a691e874919e97cb7e93f8a863868",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "bd6abc61c6677051e9ba4ea5a563dadbe4eb93c2",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "3b9e64cbfb2204672b230aba23084b7ebd3a8dd6",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "2c00b4786b1b55ba32c0d09b176ad76647f6128d",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "932e7fb7e62a691e874919e97cb7e93f8a863868",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "3b9e64cbfb2204672b230aba23084b7ebd3a8dd6",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "9e0018d6dea91589b6dbc3e5e6809a8faee29991",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "932e7fb7e62a691e874919e97cb7e93f8a863868",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Comment by sawyerawesome** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "2005",
    "commit-sha": "061bf3a6bee3e9ee077ba6d7a7023feeeb571e05",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "872",
    "commit-sha": "9e0018d6dea91589b6dbc3e5e6809a8faee29991",
    "pipeline": "master",
    "org": "aporeto-inc"
  },
  {
    "project": "",
    "component": "prismacloud",
    "pr-id": "103",
    "commit-sha": "932e7fb7e62a691e874919e97cb7e93f8a863868",
    "pipeline": "master",
    "org": "prismacloud/pcn"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
