### PR TITLE
Restricting the name of the Ruleset object to be 16 characters.

### PR DESCRIPTION
**Pull request by rramalinga**
## Description

CNS-1029 - Limit the ruleset name to 16 characters

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

@t00f @ericrpowers Can you please help with the review.

### CODE REVIEW

**Comment by rramalinga** [comment]
@t00f @ericrpowers Can you please help with the review.

**Review by t00f — APPROVED** [review]
This looks good to me! Thanks @rramalinga 👍

**Review by t00f — CHANGES_REQUESTED** [review]
Actually, you did the change on the network rule. We need to have the limitation on the Ruleset object

**Comment by t00f** [comment]
cc @vjuux @rramalinga  The limitation needs to happen on the NetworkRuleSetPolicy object

**Comment by t00f** [comment]
@vjuux @rramalinga my bad, I think you were right 👍

**Pull request merged**
