### PR TITLE
Cloud graph result mongo grid fs

### PR DESCRIPTION
**Pull request by abhijitherekar**
## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "7d5e596d0778d5aad767fbc140796247377cbbfb",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "cedca69de4d9ec07e1e0bdb3616b6e0886b5de01",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "101d307f9611e09191ffb8785ec8604619d3c2c8",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Review by rramalinga — APPROVED** [review]

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "e0c0b787c871a8cb86f92c8d65132abd3911db48",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "9c9f51ef96abb818a6203a369bce7ea6249e544c",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "97c60dc71dc23e71ad7d776ba8aec3586101fb00",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "1cc1af411ec936a2c8222918a848f0e915e05c5f",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "05022448f848b7ed8da7d0b24deb80e4c82e445d",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "8f2337a7e3f7d9145c75c7e629cedc4f75c46836",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "e0d100afebb4ccf767f9b4bc0a7ae4fbd91659c3",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  }
]
```

**Comment by abhijitherekar** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "gaia",
    "pr-id": "715",
    "commit-sha": "f32862532d269143fa8eb1f312bc4d6339ea9d70",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "prismacloud",
    "pr-id": "59",
    "commit-sha": "773d19ee7fa906ca8080315a864434e57a3207a9",
    "pipeline": "master"
  },
  {
    "project": "cloudGraphResult_mongoGridFS",
    "component": "backend",
    "pr-id": "1364",
    "commit-sha": "d87e66c02d5bb4a088ee74607b78643eba98a539",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
