### PR TITLE
Update: Align error message syntax for custom_validations

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
In the spirit of fixing https://github.com/aporeto-inc/aporeto-devs/issues/862 I decided to tackle all custom validation error messages and align them all with the same syntax. While I could have still missed a few spots, I think there is more consistent now. : )

> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/862

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "validation-syntax-alignment",
    "component": "backend",
    "pr-id": "870",
    "commit-sha": "4c052119a4dcfbae352e6f6413f90b6175dd616e",
    "pipeline": "master"
  },
  {
    "project": "validation-syntax-alignment",
    "component": "gaia",
    "pr-id": "554",
    "commit-sha": "b00b03c2bbf8549589b63abd0edcd35a462345af",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "validation-syntax-alignment",
    "component": "backend",
    "pr-id": "870",
    "commit-sha": "4c052119a4dcfbae352e6f6413f90b6175dd616e",
    "pipeline": "master"
  },
  {
    "project": "validation-syntax-alignment",
    "component": "gaia",
    "pr-id": "554",
    "commit-sha": "b00b03c2bbf8549589b63abd0edcd35a462345af",
    "pipeline": "master"
  }
]
```

**Review by t00f — COMMENTED** [review]
I think there is a rule that says that an fmt.Println() and fmt.Errorf cannot start with a capitalized letter ?

**Review by primalmotion — CHANGES_REQUESTED** [review]
When using `fmt.Errorf` the error should not capitalized or punctuated. The real problem here is that `fmt.Errorf` should not be used here in the first place. 

Validation functions must return an `elemental.Error` made using `makeValidationError` where the description must be capitalized

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "validation-syntax-alignment",
    "component": "gaia",
    "pr-id": "554",
    "commit-sha": "84b61de81ae052b1fd5384a4f90842490b60d1ed",
    "pipeline": "master"
  },
  {
    "project": "validation-syntax-alignment",
    "component": "backend",
    "pr-id": "870",
    "commit-sha": "5279d77d42036b44a40a264657d4465417d9488d",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "validation-syntax-alignment",
    "component": "backend",
    "pr-id": "870",
    "commit-sha": "5279d77d42036b44a40a264657d4465417d9488d",
    "pipeline": "master"
  },
  {
    "project": "validation-syntax-alignment",
    "component": "gaia",
    "pr-id": "554",
    "commit-sha": "bf63e135eda3b55c1763291f67e15b41afb9dad5",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]

**Pull request merged**
