### PR TITLE
Fixed: Require validity, make expirationTime read-only and use timeDuration validation on message model

### PR DESCRIPTION
**Pull request by ericrpowers**
#### Description
In the process of aligning gaia's `Message` model with backend, we also noticed that expirationTime was not read-only and we could leverage the `timeDuration` custom validation function.

> Fixes: https://github.com/aporeto-inc/aporeto-devs/issues/857

### CODE REVIEW

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "",
    "component": "backend",
    "pr-id": "865",
    "commit-sha": "f178c089e62bf776bbb676d1bb53de1f5513b632",
    "pipeline": "master"
  },
  {
    "project": "",
    "component": "gaia",
    "pr-id": "553",
    "commit-sha": "2238fdec486a56ec7944e8eccc1fb898803e86ad",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-message-model",
    "component": "backend",
    "pr-id": "867",
    "commit-sha": "0859ada67a0ce14b12542b02d01ec0a67ca353fc",
    "pipeline": "master"
  },
  {
    "project": "fix-message-model",
    "component": "gaia",
    "pr-id": "553",
    "commit-sha": "2238fdec486a56ec7944e8eccc1fb898803e86ad",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-message-model",
    "component": "backend",
    "pr-id": "867",
    "commit-sha": "0859ada67a0ce14b12542b02d01ec0a67ca353fc",
    "pipeline": "master"
  },
  {
    "project": "fix-message-model",
    "component": "gaia",
    "pr-id": "553",
    "commit-sha": "2238fdec486a56ec7944e8eccc1fb898803e86ad",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-message-model",
    "component": "backend",
    "pr-id": "867",
    "commit-sha": "4c7efd02f0d7020010d81f1dcfd402736be6b307",
    "pipeline": "master"
  },
  {
    "project": "fix-message-model",
    "component": "gaia",
    "pr-id": "553",
    "commit-sha": "347ecb0908f6fd40db814c33d8c9dabef88b993f",
    "pipeline": "master"
  }
]
```

**Comment by ericrpowers** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-message-model",
    "component": "backend",
    "pr-id": "867",
    "commit-sha": "d4df300d4bfe952f5b8a9a5789fb90816c4b1016",
    "pipeline": "master"
  },
  {
    "project": "fix-message-model",
    "component": "gaia",
    "pr-id": "553",
    "commit-sha": "347ecb0908f6fd40db814c33d8c9dabef88b993f",
    "pipeline": "master"
  }
]
```

**Review by t00f — APPROVED** [review]
Better validation 👍

**Review by primalmotion — APPROVED** [review]

**Pull request merged**
