### PR TITLE
fix: vmss support

### PR DESCRIPTION
**Pull request by rramalinga**
- Creating a new gaia object called scale set which would represent the VMSS object in Azure
- The object will hold the backend pool information if the VMSS is part of a Load Balancer backend pool

### CODE REVIEW

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-vmss-support",
    "component": "backend",
    "pr-id": "1665",
    "commit-sha": "c83522bb13961ae87cac741bc50b1265b2811e77",
    "pipeline": "master"
  },
  {
    "project": "fix-vmss-support",
    "component": "gaia",
    "pr-id": "792",
    "commit-sha": "eecb031e810cf27929650efe1685a1fc79be2291",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-vmss-support",
    "component": "backend",
    "pr-id": "1665",
    "commit-sha": "9658358a38e025ae73fb30336a9dec36d7237a44",
    "pipeline": "master"
  },
  {
    "project": "fix-vmss-support",
    "component": "gaia",
    "pr-id": "792",
    "commit-sha": "eecb031e810cf27929650efe1685a1fc79be2291",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-vmss-support",
    "component": "gaia",
    "pr-id": "792",
    "commit-sha": "eecb031e810cf27929650efe1685a1fc79be2291",
    "pipeline": "master"
  },
  {
    "project": "fix-vmss-support",
    "component": "backend",
    "pr-id": "1665",
    "commit-sha": "9658358a38e025ae73fb30336a9dec36d7237a44",
    "pipeline": "master"
  }
]
```

**Comment by rramalinga** [comment]
/build - automatically fired by gogo with following PRs and commit SHAs v1.0.0
```
[
  {
    "project": "fix-vmss-support",
    "component": "backend",
    "pr-id": "1665",
    "commit-sha": "9658358a38e025ae73fb30336a9dec36d7237a44",
    "pipeline": "master"
  },
  {
    "project": "fix-vmss-support",
    "component": "gaia",
    "pr-id": "792",
    "commit-sha": "7362e3878df3b4bb4a969aeb73cd60fd5f554bf7",
    "pipeline": "master"
  }
]
```

**Review by abhijitherekar — APPROVED** [review]

**Pull request merged**
